roles/ncn-common-setup/files/srv/cray/scripts/common/cleanup-kis-artifacts.sh
roles/ncn-common-setup/files/srv/cray/scripts/common/create-kdump-artifacts.sh
roles/ncn-common-setup/files/srv/cray/scripts/common/create-kexec-initrd.sh
roles/ncn-common-setup/files/srv/cray/scripts/common/create-kis-artifacts.sh
roles/ncn-common-setup/files/srv/cray/scripts/common/dracut-lib.sh

- Fixes: MTL-1761
We often repeat static inputs to dracut in our scripts, this adds a library and updates the following scripts to use the library:
- `create-ims-initrd.sh`
- `create-kdump-artifacts.sh`
- `create-kexec-initrd.sh`
- `create-kis-artifacts.sh`
Each script was tested on metal to verify that the modifications worked.
Lastly this also resolves an old problem where a mount point would exist after running `create-kis-artifacts.sh`:
```bash
redbull-ncn-m001-pit: # mount | grep 'squashfs-root'
/dev/sdd4 on /var/www/ephemeral/data/k8s/0.3.12/squashfs-root/mnt/squashfs type ext4 (rw,noatime)
redbull-ncn-m001-pit: #umount /var/www/ephemeral/data/k8s/0.3.12/squashfs-root/mnt/squashfs
```
That was fixed by adding a `trap` to `create-kis-artifacts.sh` that `umounts` …

MTL-1761 Use a library for storing dracut inputs

---

.github/PULL_REQUEST_TEMPLATE.md

- Fixes: task-checklist gate
This allows checkboxes to be checked off for build-only related items, meaning we can still use the task-list as a gate.

Add clauses to allow checkboxes to be applicable to build only items

---

roles/ncn-common-setup/defaults/main.yml
roles/ncn-common-setup/tasks/gcp.yml
roles/ncn-common-setup/tasks/metal.yml

https://jira-pro.its.hpecorp.net:8443/browse/MTL-1735
Moves the logic from the common layer setup.sh scripts:
- **boxes/ncn-common/provisioners/google/setup.sh** -> **roles/ncn-common-setup/tasks/gcp.yml**
- **boxes/ncn-common/provisioners/metal/setup.sh** -> **roles/ncn-common-setup/tasks/metal.yml**
Note: node-images/boxes/ncn-common/provisioners/common/setup.sh will remain as a shell provisioner because it expands the disk and installs ansible.
Ansible migration. 
bash script build logic was ported to ansible as idempotently as it can be right now.

MTL-1735 Migrate setup.sh build steps

---

roles/ncn-common-setup/files/srv/cray/scripts/common/create-kdump-artifacts.sh
roles/ncn-common-setup/files/srv/cray/scripts/common/dracut-lib.sh

CASMTRIAGE-3591 Reduce kdump script

---

roles/ncn-common-setup/files/tests/metal/goss-image-common.yaml
roles/ncn-common-setup/tasks/metal.yml

- Relates to: MTL-1841
The metal tasks in `ncn-common-setup` were _not_ invoking a task to actually parse `services_metal`. This mean that some services were not starting or stopping as desired.

MTL-1841 Missed daemon setup

---

roles/ncn-common/files/resources/metal/cloud/cloud.cfg.d/05_logging.cfg
roles/ncn-common/files/resources/metal/systemd/cloud-init-oneshot.service
roles/ncn-common/tasks/common.yml
roles/ncn-common/vars/metal.yml

- Relates to: #21 
`cloud.cfg` is in the wrong place, and `cloud-init-oneshot.service` is used and needs to be restored.

MTL-1858 restore `cloud-init-oneshot.service`

---

roles/ncn-common/files/tests/common/ncn-common-tests.yml
roles/ncn-common/vars/common.yml

- Fixes: MTL-1869
- Relates to: #21 #22 
Disables `postfix.service`, causing the `You have new mail` notifications to cease.

MTL-1869 Disable `postfix.service`

---

roles/ncn-common/files/scripts/metal/metal-lib.sh

- Fixes: MTL-1872
Fix the empty `/tmp/bbs` files for disk entries by using case-insensitive matching.

MTL-1872 `setup_uefi_bootorder`

---

roles/ncn-common/files/tests/google/ncn-common-tests.yml

The kdump test seems to flake, we do not need to check if it is running in the pipeline. We can't only check if it's enabled, the goss test needs to look for enabled & running states.

Remove kdump test

---

roles/ncn-common/defaults/main.yml

CASMINST-4884: add `rpcrdma` to the kernel module blacklist

---

roles/ncn-common/files/tests/common/ncn-common-tests.yml

The `rpm` command was giving an error:
```bash
rpm -q | grep kernel-default | wc -l
rpm: no arguments given for query
0
```
Changing it from `rpm -qa` to `rpm -q` was done incorrectly, the `grep` needed to be removed. This PR fixes it:
```bash
rpm -q kernel-default | wc -l
1
```

MTL-1905 bad input to `rpm`

---

pb_ncn_common.yml
pb_ncn_common_team.yml

- Relates to: MTL-1865
The current Ansible assumes all builds use `root`, which is untrue when we add builds like Vagrant.

MTL-1865 Allow non-root to escalate

---

roles/ncn-common/files/scripts/common/create-ims-initrd.sh
roles/ncn-common/files/scripts/metal/metal-lib.sh

- Fixes: MTL-1876
- Relates to: CASMINST-4849
Install the initrd and kernel from the booted squashFS instead of relying on dracut to fetch it.
This is needed for pre-signed URLs to work, because we won't be able to fetch a pre-signed URL for the initrd and kernel during dracut. The pre-signed URL for the initrd and kernel are only available to iPXE (and not dracut).
Update the `create-ims-initrd.sh` script to populate `/squashfs` so the bootloader code can grab up-to-date artifacts from IMS builds.

MTL-1876 Install initrd and kernel

---

roles/ncn-common/files/scripts/metal/metal-lib.sh

- Relates to: MTL-1926 (discovered while working on MTL-1926 in triage)
In cases where `install_grub2` is invoked by itself as a workaround and if `/metal/recovery` isn't already mounted then the function fails.

MTL-1926 `-t` is incorrect

---

roles/ncn-common/files/scripts/common/create-ims-initrd.sh

Force the dmsquash-live module to be added to the initrd.  Without it, NCNs can't boot.
- Fixes: MTL-1930

MTL-1930: force-add dmsquash-live

---

roles/ncn-common/files/scripts/common/create-ims-initrd.sh

- Fixes: CASMREL-1091
The old kdump image needs to be purged so that a new one can be regenerated that matches symbols and other details of the new initrd.

CASMREL-1091 Remove kdump initrd for regen

---

roles/ncn-common/files/scripts/google/cloudinit.sh

- Fixes: VSHA-468
This needs to cease and desist for vshasta to be able to preserve the `authorized_keys` it wants to set up.

VSHA-468 Stop setting up `authorized_keys`

---

roles/ncn-common/files/scripts/common/chrony/csm_ntp.py

CASMTRIAGE-4255: sync up csm version of csm_ntp.py with the NCN version

---

roles/ncn-common/files/scripts/google/cloudinit.sh
roles/ncn-common/files/sysctl/common/98-cray-arp.conf

- Fixes: VSHA-468
This creates `/root/.ssh` for the subsequent commands in `cloudinit.sh` to work.

VSHA-468 `/root/.ssh` does not exist

---

roles/ncn-common/tasks/vagrant.yml
roles/ncn-common/vars/vagrant.yml

- Relates to: CASMINST-5313
Disable systemd services that Dennis is disabling in his `.qcow2` box conversion scripts in the Vagrant OS test harness.

CASMINST-5313 Vagrant systemd services

---

roles/ncn-common/files/sysctl/common/99-cray-ncn-network-common.conf
roles/ncn-common/files/sysctl/google/99-google-network-common.conf
roles/ncn-common/files/sysctl/metal/99-metal-ncn-common.conf
roles/ncn-common/files/sysctl/metal/991-sma-ldms.conf

- Fixes: MTL-1974
This removes `sysctl` settings that conflict with what system integration will set, these settings are very stale and metal/CSM does not care what they are set to.
This also cleans up some duplicates, and unused settings such as ones touching `docker0` (which isn't used in Shasta V1.4 or newer).
Lastly this adds license headers and sorts the files.

MTL-1974 Cleanup `sysctl` settings

---

roles/ncn-common/files/scripts/metal/cleanup.sh

- Fixes: MTL-1871
Adds a `cleanup.sh` script for purging unused or all images from the SQFSRAID.
**Running with no arguments:**
```bash
/srv/cray/scripts/common/cleanup-image-storage.sh
Image storage status:
Size: 23G
Used: 15G
Current used image directory is [LiveOS]
Found the following unused image directories:
1.3.0-alpha.23	4.5G
1.3.0-alpha.25	4.5G
Proceed to cleanup listed image directories? [y/n]:y
Removing image directories ...
Done
```
**Running with `-y`:**
```bash
Image storage status:
Size: 23G
Used: 15G
Current used image directory is: [/run/initramfs/live/1.3.0-alpha.28]
Found the following unused image directories:
1.3.0-alpha.23	4.5G
LiveOS	6.0G
Proceed to cleanup listed image directories? [y/n]:y
Removing image directories ...
Done
```
**Running with …

MTL-1871 `cleanup.sh`

---

roles/ncn-common/files/tests/google/ncn-common-tests.yml
roles/ncn-common/vars/google.yml

- Relates to: MTL-1708
`google-osconfig-agent.service` is no longer instlled in SP4.

MTL-1708 `google-osconfig-agent.service`

---

roles/node-images-base/files/scripts/common/create-ims-initrd.sh
roles/node-images-base/files/scripts/common/dracut-lib.sh

- Relates to: MTL-2012
`livenet` is needed to use URLs with the `root=` argument, this is necessary for application and compute images.
Harmless to include in NCN images, already a part of the NCN IMS rebuilds.

MTL-2012 Add `livenet`

---

roles/ncn-common-cos/vars/common.yml
roles/ncn-common/vars/common.yml

- Relates to: MTL-1708
`csm-node-identity` is not a COS package.

MTL-1708 Move `csm-node-identity` to `ncn-common`

---

roles/ncn-common/files/resources/metal/dracut.conf.d/00-ncn.conf

- Fixes: VSHA-524
`kdump`'s initramFS does not include `nvme` drivers, these are a necessesity for both upcoming V2 hardware and for vshastav2.

VSHA-524 Include `nvme` drivers

---

roles/node-images-base/tasks/common.yml

- Fixes: MTL-1828
Currently our operational docs have users manually remove the default pool from `/etc/chrony.conf`. I noticed that the pool is already commented out by default, but perhaps something comments it back in - either way this change implements the doc step and allows us to remove the doc step.
The JIRA itself also describes the need to remove
`/etc/chrony.d/pool.conf`, this change also removes that file.

MTL-1828 Remove default NTP pool

---

roles/node-images-base/files/scripts/metal/cleanup-kis-artifacts.sh
roles/node-images-base/files/scripts/metal/create-kis-artifacts.sh

- Relates to: MTL-1476
MTL-1476 is adding a new script in `node-images` that requires `create-kis-artifacts.sh`, the new script is for metal only. The `create-kis-artifacts.sh` script technically is also metal only, so to prevent a confusing connection of a metal-only script requiring another metal-only script that lives in `common/` this is moving `create-kis-artifacts.sh` and its cleanup script to `metal/`.
This also updates the copyrights.

MTL-1476 Move `create-kis-artifacts.sh` to `metal/`

---

roles/node-images-base/files/resources/metal/dracut.conf.d/00-metal.conf

- Relates to: MTL-1476
The initramFS created for the pre-install-toolkit is lacking the `ext4` module. Adding it to our `dracut.conf.d` will ensure it is included.
Without the module the ext4 OverlayFS fails to load on pre-install-toolkits created by node-images.
```bash
sh-4.4# blkid | grep cow
/dev/sdb3: LABEL="cow" UUID="233b15c2-6c85-4191-906c-69b587eb2ce0" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="df0e7239-138b-4064-9ed2-4deaaba33395"
sh-4.4# mount /dev/sdb3 /mnt
mount: /mnt: unknown filesystem type 'ext4'.
sh-4.4# insmod ext4
insmod: ERROR: could not load module ext4: No such file or directory
```

MTL-1476 Need `ext4`

---

roles/node-images-base/tasks/common.yml

- Fixes: MTL-2077
Tested on a running system:
```yaml
---
- hosts: localhost
tasks:
- lineinfile:
path: /root/.bashrc
line: "alias ll='ls -l --color'"
owner: root
regexp: "^alias ll='.*$"
state: present
insertafter: EOF
create: True
```
```bash
ncn-m001:~ # cat .bashrc
source <(kubectl completion bash)
(csm_ansible) ncn-m001:~ # ansible-playbook t.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
PLAY [localhost] ***************************************************************************************************************************
TASK [Gathering Facts] *************************************************************** …
```

MTL-2077 Add `ll` alias for GNU `ls`

---

roles/node-images-base/files/resources/metal/dracut.conf.d/00-metal.conf

- Relates to: VSHA-536
`vfat` is used by our images, specifically in the disk bootloader. It's automatically included when `create-kis-artifact.sh` is invoked in our build pipeline and on a metal NCN. However it was not included when `create-kis-artifacts.sh` was invoked in vshastav2.
Explicitly including it will ensure it's always included.

VSHA-536 Include `vfat`

---

roles/node-images-base/files/resources/metal/dracut.conf.d/00-metal.conf
roles/node-images-base/files/scripts/metal/create-kis-artifacts.sh

- Fixes: VSHA-536
- Relates to: #74 
- Fix `codepage cp437 not found` errors from development workflows; ensure we always have our necessary modules for all of our filesystems.
In vshasta, in my dev flow, I am hitting instances where `nls_cp437` is missing.
Add in the `nls_cp437` code page filesystem, the `fat` FS module, and the `nls_iso8859_1` character set.
```
[  112.731034][ T2076] FAT-fs (md127): codepage cp437 not found
[  112.729706] dracut-initqueue[2076]: mount: /sysroot: wrong fs type, bad option, bad superblock on /dev/md127, missing codepage or helper program, or other error.
```
I have hit this error before when I was experimenting with `fat` for a `kdump` dumping partition. ![Screenshot_20230214-025828.png](https://user-images.githubusercontent.com/7772 …

VSHA-536 kdump and cp437

---

pb_node_images_application.yml
roles/node-images-application/defaults/main.yml
roles/node-images-application/files/resources/cloud.cfg
roles/node-images-application/files/resources/cmdline-perm.service
roles/node-images-application/tasks/common.yml
roles/node-images-application/tasks/google.yml
roles/node-images-application/tasks/main.yml
roles/node-images-application/tasks/metal.yml
roles/node-images-application/tasks/vagrant.yml
roles/node-images-application/vars/common.yml
roles/node-images-application/vars/google.yml
roles/node-images-application/vars/metal.yml
roles/node-images-application/vars/vagrant.yml

- Relates to: https://jira-pro.its.hpecorp.net:8443/browse/MTL-2004
Adds an ansible provisioner and adds the framework for additional ansible code for the application image.

MTL-2004 application image

---

roles/compute/files/resources/cmdline-perm.service
roles/compute/tasks/common.yml

https://jira-pro.its.hpecorp.net:8443/browse/CASM-3071
- adds service to change permissions on /proc/cmdline (requested by Alan M.) 
- enables needed services
- adds misc. directories

Compute fixes

---

roles/ncn-common/files/resources/metal/systemd/metalfs.service

masters have ETCDK8S. workers have K8SLET.  grep for "K8S" to catch both.
- Fixes: MTL-2127

MTL-2127: tweak the grep so it works on masters *and* workers

---

roles/ncn-common/files/resources/metal/systemd/metalfs.service

MTL-2127: check for the BOOTRAID label, which exists on all node types

---

roles/node-images-ncn-common/tasks/metal.yml
roles/node-images-ncn-common/tasks/vagrant.yml
roles/node-images-ncn-common/vars/google.yml

- Relates to: #83 
Some changes made it into the `vendor/` directory instead of the metal-provision repo: https://github.com/Cray-HPE/node-images/pull/718/commits/34f1a581eaa39826347da89c2fa0d64a2804936b#diff-8d9d936a0569c9517bcc3d67a59381e9c45f39560503607883e4305a543906e1
Follow-up PR to #83.

CASMINST-4571 pt2

---

roles/node-images-ncn-common/vars/packages/suse.yml
roles/node-images-storage-ceph/vars/packages/suse.yml

- Relates to: CASMINST-4571
Artifactory had ceph RPMs for version 16 hiding in the csm-rpms RPM repository, and since that repository had a higher priority than the filesystems-ceph one we had to use the `>` or `>=` operator to force selection of `ceph-17`. However this had a pitfall, now that ceph-17.2.6 is available its packages were being chosen over our desired 17.2.5 RPMs.
We've removed the ceph RPMs from csm-rpms, which were uploaded by Pete a long time ago as an attempted workaround for a CSM tarball. In doing so, using `ceph<17.2.6` now properly resolves 17.2.5 (instead of the old 16.2.9 RPMs).

Use an upperbound for ceph

---

roles/node-images-ncn-common/vars/google.yml

- Relates to: #91 
The A-Z ordering breaks the registration task:
```bash
Error: Registration server returned 'The product you are attempting to activate (Public Cloud Module 15 SP4 x86_64) requires one of these products to be activated first: Server Applications Module 15 SP4 x86_64' (422)
```

Fix ordering of SUSE modules

---

roles/node-images-kubernetes/vars/services/suse.yml
roles/node-images-storage-ceph/vars/services/suse.yml

- Fixes: Errors that spire failed to start
`spire-agent` regressed and was enabled when it shouldn't have been. It should only be enabled/started on NCNs when the
`join-spire-on-storage.sh` script is invoked.

Disable `spire-agent`

---

roles/node-images-base/vars/packages/suse.yml

Add tenant configuration option, pass cray-tenant-name header value if specified.
* https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6319
Configuration without tenant:
```
ncn-w001:~/.config/cray/configurations # cray init
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Cray Hostname: https://api-gw-service-nmn.local/
Tenant Name (leave blank for global scope): []:
Username: vers
Password:
Success!
Initialization complete.
ncn-w001:~/.config/cray/configurations # cat default
[core]
hostname = "https://api-gw-service-nmn.local/"
tenant = ""
[auth.login]
username = "vers"
```
Configuration without tenant:
```
ncn-w001:~/.config/cray/configurations # cray init
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Cray …
```

Add tenant name/id header when scoped to tenant (CASMPET-6319)

---

roles/node-images-ncn-common/files/tests/common/ncn-common-tests.yml
roles/node-images-ncn-common/files/tests/google/ncn-common-tests.yml
roles/node-images-ncn-common/files/tests/metal/ncn-common-tests.yml

The changes from #104 required refactoring the tests for `metalfs` as well.

Missed test refactor

---

roles/node-images-pre-install-toolkit/tasks/main.yml

The build will fail with the following message since kdump can't find `cow`:
```
/usr/lib/dracut/modules.d/99kdump/module-setup.sh: line 74: host_fs_types["$_dev"]: bad array subscript
dracut module 'kdump' cannot be found or installed.
```

`cow` not existing during the build causes buildfailure

---

roles/node-images-ncn-common/vars/packages/suse.yml

- Fixes:
- Requires:
- Relates to:
CASMTRIAGE-5309
Bump CSM-scripts version

CASMTRIAGE-5309 Update CSM-scripts

---

scripts/packer/setup-functions.sh

Include a function for installing the `SLE_HPC-release` package, fixing any need to duplicate this method in their provisioner blocks.
I want to remove the function [out of ncn-common](https://github.com/Cray-HPE/node-images/blob/main/boxes/ncn-common/provisioners/metal/install.sh#L27-L34) since we install SLE_HPC-release in the base image now ([implicitly](https://github.com/Cray-HPE/node-images/blob/main/boxes/sles15-base/http/autoinst.template.xml#L124)). I want this function because if the implicit install ever ceases, I want a common method for ensuring the RPM is installed.

Add HPC Release function

---

roles/node-images-hypervisor/vars/services/debian.yml
roles/node-images-hypervisor/vars/services/rhel.yml

- Relates to: #114 
The Ansible var file is invalid.
Also fix extra empty line.
I discovered this via the ansible-lint plugin which was ignored in the PR because it's failing all the time. I have an incoming PR to fix the linter so we can actually consider/rely on it.

Fix broken comment making invalid Ansible

---

roles/node-images-ncn-common/vars/packages/suse.yml

Reverts aws-cli due to missing/incompatible dependencies, including python3-botocore.

MTL-2154: Revert aws-cli due to incompatible dependencies

---

roles/node-images-base/vars/packages/suse.yml
roles/node-images-ncn-common/vars/packages/suse.yml

Upgrades google-guest-agent due to a break in the build.

MTL-2154: Upgrade google-guest-agent

---

roles/node-images-base/vars/packages/suse.yml

Adds support for arm64 to the IMS cray cli api.
- Fixes: CASMCMS-8565](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8565)
Adds support for arm64 to the IMS cray cli api.
If this version of the craycli is installed on a system that doesn't have the update IMS service, the existing api will work perfectly fine and the new arguments will just cause failures. 
Low risk

CASMCMS-8565 - update ims craycli api to include arch and require-dkms arguments.

---

roles/node-images-application/vars/packages/suse-x86_64.yml
roles/node-images-compute/vars/packages/suse-x86_64.yml
roles/node-images-ncn-common/vars/packages/suse.yml

CSM manifests require newest cfs-state-reporter to be updated. New version includes noarch RPM changes for CASMCMS-8603
- Fixes: [CASMCMS-8603](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8603)
- Feature PR
New cfs-state-reporter rpm is now being built as a `noarch` BuildArch

CASMCMS-8603: Update cfs-state-reporter

---

roles/node_images_application/vars/packages/suse-x86_64.yml
roles/node_images_application/vars/packages/suse.yml
roles/node_images_compute/vars/packages/suse-x86_64.yml
roles/node_images_compute/vars/packages/suse.yml

- Fixes: CASMCMS-8603
- Relates to: #126 
cfs-state-reporter is now noarch and does not need to be listed in the x86_64 only repos.
I missed this in https://github.com/Cray-HPE/metal-provision/pull/126, so this PR is just moving things around.

CASMCMS-8603 cfs-state-reporter is noarch

---

Jenkinsfile.github
roles/node_images_application/vars/packages/suse-x86_64.yml
roles/node_images_application/vars/packages/suse.yml
roles/node_images_compute/vars/packages/suse-x86_64.yml
roles/node_images_compute/vars/packages/suse.yml
scripts/update-package-versions.sh

- Jenkinsfile actually validates packages now
- move cfs-state-reporter into x86_64 package files

Fix package check

---

roles/node_images_kubernetes/vars/packages/suse.yml
roles/node_images_ncn_common/files/scripts/metal/metal-lib.sh

- Fixes: MTL-2156
This PR addresses three issues:
1. Stop baking the cray-cmstools-crayctldeploy rpm into the image - install it via cloud-init
2. Dynamically discover which csm-sle repos are available
3.  Don't `exit 1` when nexus is unavailable.  This is an expected condition during initial NCN deployment.
Tested by copying metal-lib.sh to surtur, sourcing it, and running `install_csm_rpms`:
```
ncn-m001:~/heemstra # install_csm_rpms
install_csm_rpms will search the following repos: csm-sle-15sp4 csm-sle-15sp2 csm-sle-15sp3
Loading repository data...
Reading installed packages...
'cray-cmstools-crayctldeploy = 0:1.10.8-1' is already installed.
No update candidate for 'cray-cmstools-crayctldeploy-1.10.8-1.x86_64'. The highest available version is …
```

 MTL-2156: don't bake cray-cmstools-crayctldeploy into the image

---

roles/node_images_compute/vars/packages/suse-x86_64.yml

ARM work defined in epic [CASM-4066](https://jira-pro.its.hpecorp.net:8443/browse/CASM-4066) requires that RPMs be built as `noarch` from `x86_64`
- Fixes: [CASMCMS-8604](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8604)
- Relates to: CASMCMS-8517

CASMCMS-8604: Updating rpms for bos-reporter

---

roles/node_images_ncn_common/files/metal/cloud/cloud.cfg.d/05_logging.cfg

- Fixes: MTL-2161
- Relates to: #121 
The `05_logging.cfg` file was incorrectly formatted and was not in a recognizable YAML structure. This was causing cloud-init to fail configuring its logging, this entailed throwing non-fatal errors and extra log spam into the console.

MTL-2161 Reformat cloud-init log config file

---

roles/node_images_base/vars/packages/suse.yml
roles/node_images_ncn_common/vars/packages/suse.yml

- Fixes: CASMINST-6379
Replaces the old, malconfigured `hpe-csm-yq-package` with a new, maintained package. This properly states it provides `yq`, which allows us to install packages dependent on `yq` such as `yq-bash-completion`. The old `hpe-csm-yq-package` provided a `/usr/bin/yq`, `/usr/bin/yq3`, and `/usr/bin/yq4` binary. The new `hpe-yq` package provides the same binaries, but a newer version for `/usr/bin/yq4`.

CASMINST-6379 New `hpe-yq` package

---

roles/node_images_kubernetes/vars/packages/suse.yml

CASMPET-6397 requires it.
- Fixes: MTL-2163

MTL-2163: platform-utils must remain baked into the image

---

roles/node_images_hypervisor/defaults/main.yml
roles/node_images_hypervisor/tasks/main.yml

PR #145 removed `vagrant`, so these tasks also need to go.

No vagrant

---

roles/node_images_kubernetes/vars/packages/suse.yml
roles/node_images_ncn_common/vars/packages/suse.yml

Update NCN image to K8S v1.22.13
* https://jira-pro.its.hpecorp.net:8443/browse/CASM-3290
Verified image on redbull:
```
ncn-m002:~ # kubectl get nodes
NAME       STATUS   ROLES                  AGE   VERSION
ncn-m002   Ready    control-plane,master   17h   v1.22.13
ncn-m003   Ready    control-plane,master   17h   v1.22.13
```
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing

Update K8s images for CSM 1.5 to have K8s 1.22 (CASMINST-6374)

---

scripts/repos/cray.template.repos

- Fixes: CASMINST-3421
- Requires: https://github.com/Cray-HPE/utils/pull/71
- Relates to: CASMINST-6410
This adds the `noos` repository.
CASMINST-6410: `platform-utils` is now available from `sle-15sp4` and `noos`, the `sle-15sp2` repository is no longer needed.

CASMINST-3421 add `noos` repo (CASMINST-6410)

---

roles/node_images_pre_install_toolkit/vars/packages/suse.yml
scripts/nexus/nexus-ssl.conf
scripts/nexus/setup-nexus.sh

- Relates to: #122 
CSM repos usually have the `CSM_RELEASE` (or some dynamic value) in their repo name. Mimmic this in PIT repos, and then use a YUM repo group with a common name for cloud-init to refer to.

MTL-2032 Add repo groups

---

roles/node_images_compute/vars/packages/suse-x86_64.yml
roles/node_images_ncn_common/vars/packages/suse.yml

- Fixes: [CASMCMS-8621](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8621)
- CSM manifest pr - https://github.com/Cray-HPE/csm/pull/2261
Change updates to latest cfs-trust which publishes noarch rpms.

CASMCSM-8621: Updating cfs-trust to 1.6.4

---

roles/node_images_compute/vars/packages/suse-x86_64.yml
roles/node_images_ncn_common/vars/packages/suse.yml

Backport of https://github.com/Cray-HPE/csm/pull/2261

CASMCMS-8621: Add noarch rpms support for cfs-trust

---

roles/node_images_pre_install_toolkit/vars/packages/suse.yml
scripts/repos/cray.template.repos

- Fixes: CASMINST-6333 and MTL-2165
- New ilorest:  
- New cray-site-init: https://github.com/Cray-HPE/cray-site-init/pull/310/files

MTL-2165 and CASMINST-6333

---

roles/node_images_base/vars/packages/suse.yml
roles/node_images_compute/vars/packages/suse-aarch64.yml
roles/node_images_compute/vars/packages/suse-x86_64.yml
roles/node_images_compute/vars/packages/suse.yml
scripts/repos/compute.template.repos
scripts/repos/suse.template.repos

- lower COS repo priority to match csm-rpms
- temporarily disable gpg check on opensuse Cloud:Tools repo
- update google-guest-agent version

repo priority, disable gpg check, version update

---

roles/node_images_base/vars/packages/suse.yml
scripts/repos/suse.template.repos

- temporarily disable gpg check on opensuse Cloud:Tools repo
- update google-guest-agent version
Ticket to revert gpg check disable: https://jira-pro.it.hpe.com:8443/browse/MTL-2169

disable gpg check, version update

---

scripts/repos/suse.template.repos

gpg check was disabled on opensuse Cloud:Tools repo. re-enabling gpg check
- Fixes: https://jira-pro.it.hpe.com:8443/browse/MTL-2169

MTL-2169 - re-enable gpg check Cloud:Tools

---

scripts/repos/compute.template.repos
scripts/repos/suse.template.repos

- drop COS repo priority to match csm-rpms
- re-enable cloud:tools repo gpg check
https://jira-pro.it.hpe.com:8443/browse/MTL-2169

MTL-2169 lts/csm-1.5

---

roles/node_images_base/vars/packages/suse.yml

- another another google-guest-agent version update

google-guest-agent version backport 1.5

---

roles/node_images_base/vars/packages/suse.yml

Switch craycli from deprecated keycloak client
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6640
Tested on ashton during MT OPA demo
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing

Change craycli to use shasta keycloak client instead of deprecated cray client (CASMPET-6640)

---

roles/node_images_base/vars/packages/suse.yml

The google-guest packages have inadvertently changed vendor to the openSUSE variant. The openSUSE variant changes too frequently, this is causing headaches in node-image builds and CSM tarball creation.

Downgrade back to SLE google-guest packages

---

roles/node_images_base/vars/packages/suse-x86_64.yml

- Fixes: MTL-2170
- Relates to: CASMTRIAGE-5033
QLogic has requested that we pull in their latest driver and soak it for the CASMTRIAGE-5033 issue.

MTL-2170 New QLogic 8.72.4.1 Driver

---

roles/node_images_base/vars/packages/suse.yml

CASMTRIAGE-5555: newer craycli

---

roles/node_images_hypervisor/vars/packages/suse.yml

Installs `pulumi`, an infrastructure as code application for manageing VM deployments. This application requires `python310` and `go1.20`; the former is already installed in our image, the latter is now installed alongside `pulumi`.
Also includes `qemu-ui-spice-core`, a needed dependency for setting up monitors on the VMs. This dependency fixes the `spice support is disabled` error. 
**Failure** (no `qemu-ui-spice-core`)
```bash
hypervisor:~/manderson/sles-development-box/Development/pulumi # pulumi up
Previewing update (kubernetes-cluster):
Type                     Name                                     Plan
pulumi:pulumi:Stack      libvirt-py-vm-kubernetes-cluster
+   ├─ libvirt:index:Domain  libvirt-ex-kubernetes-cluster-vm-0       create
+   ├─ libvirt:index:Domain …
```

Adds `pulumi` with spice support

---

roles/node_images_pre_install_toolkit/vars/packages/suse.yml

These three packages have new versions from some CI fixes.
`metal-basecamp` also includes some updated dependencies.

MTL-2171 CI Fixes

---

roles/node_images_pre_install_toolkit/files/apache2/nexus.conf

- Fixes:
- Requires:
- Relates to:
Everything is resolving to nexus.
This fixes non nexus URLs so they are not proxied.
Tested with the following cases
Before (broken):
```
10.252.1.4         - nexus
pit                - nexus
pit.nmn            - nexus
packages           - nexus
packages.nmn       - nexus
```
Now (fixed):
```
10.252.1.4         - pit
pit                - pit
pit.nmn.           - pit
packages.          - nexus
packages.nmn       - nexus
```
It is unclear when this broke, because 1.5 deployments have been running with a `nexus.conf` installed.

MTL-2032 Fix pit and package URLs

---

roles/node_images_base/vars/packages/suse.yml

https://github.com/Cray-HPE/csm/pull/2486

CASMCMS-8599: Add CLI support for BOS v2 session include_disabled option

---

roles/node_images_pre_install_toolkit/vars/packages/suse.yml

CASM-4366: Upgrade pit-observability images (Grafana and prometheus) to the latest version

---

roles/node_images_pre_install_toolkit/vars/packages/suse.yml

Relates to:
- https://github.com/Cray-HPE/cray-site-init/pull/324
- https://github.com/Cray-HPE/pit-init/pull/70
These changes provide functionality for MTL-2000 and can safely be included now to set the stage for toggling the MTL-2000 feature on.

MTL-2000 Staging changes

---

roles/node_images_base/vars/packages/suse.yml

Change --tenant argument to be optional to prevent BW incompatible change for non-interactive use cases.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6649
Tested on ashton:
```
ncn-m003:~/.config/cray/configurations # cray init --hostname https://api-gw-service-nmn.local
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Username: vshasta
Password:
Success!
Initialization complete.
ncn-m003:~/.config/cray/configurations # cat default
[core]
hostname = "https://api-gw-service-nmn.local"
tenant = ""
[auth.login]
username = "vshasta"
```
```
ncn-m003:~/.config/cray/configurations # cray init --hostname https://api-gw-service-nmn.local --tenant vcluster-blue
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Username: …
```

Remove required tenant prompt when initializing (CASMPET-6649)

---

scripts/nexus/setup-nexus.sh

The `exists` variable was checking the member name instead of the group repo name, this was leading the code to believe the repo group already existed and it was doing a `PATCH` which doesn't work.
This fixes the code to properly use `repo_group_name where necessary, and successfully creates the repo group.
```bash
Updating existing repo 'csm-1.5.0-beta.15-noos' ... Done
Updating existing repo group 'csm-1.5.0-beta.15-noos' with: csm-1.5.0-beta.15-noos ... Done
Uploading /var/www/ephemeral/csm-1.5.0-beta.15/rpm/cray/csm/noos to csm-1.5.0-beta.15-noos ..
```
``bash
Updating existing repo 'csm-1.5.0-beta.15-noos' ... Done
Creating repo group 'csm-noos' with: csm-1.5.0-beta.15-noos ... Done
Uploading /var/www/ephemeral/csm-1.5.0-beta.15/rpm/cray/csm/noos to …

MTL-2032 Fix group repo names

---

ansible.cfg
roles/node_images_base/vars/packages/suse.yml
roles/node_images_ncn_common/vars/packages/suse.yml
roles/node_images_storage_ceph/vars/packages/suse.yml

Backport of #234 
Changes:
- CVE updates
- Move ansible stdout_callback into ansible.cfg
- Fixes: https://jira-pro.it.hpe.com:8443/browse/MTL-2159 
- Relates to: https://jira-pro.it.hpe.com:8443/browse/MTL-2188
CVE's addressed:
- SUSE-SU-2023:2667-1
- SUSE-SU-2023:2179-1
- SUSE-SU-2023:0310-1
- SUSE-SU-2022:0805-1
- SUSE-SU-2021:2817-1
- SUSE-SU-2023:0375-1
- SUSE-SU-2023:0631-1
- SUSE-SU-2023:0343-1
- SUSE-SU-2022:3745-1

MTL-2159 backport lts/csm-1.5

---

roles/node_images_pre_install_toolkit/vars/packages/suse.yml

bump canu version
- Fixes: CASMNET-2146
- Requires:
- Relates to:

CASMNET-2146  Bump canu

---

roles/node_images_pre_install_toolkit/vars/packages/suse.yml

- Fixes: CASMNET-2146
- Requires:
- Relates to:

CASMNET-2146 bump canu

---

roles/node_images_storage_ceph/vars/packages/suse.yml
scripts/nexus/setup-nexus.sh

Upload docker images in tarball to pit-nexus. This is done already before CSM services are deployed. This is just moving this step earlier in the process so that storage nodes can use the container images in pit nexus when the storage nodes boot.
- Relates to: CASMPET-6650

CASMPET-6650 upload docker images in tarball to nexus in setup-nexus.sh

---

roles/node_images_storage_ceph/vars/packages/suse.yml
scripts/nexus/setup-nexus.sh

Upload docker images in tarball to pit-nexus. This is done already before CSM services are deployed. This is just moving this step earlier in the process so that storage nodes can use the container images in pit nexus when the storage nodes boot.
Relates to: [CASMPET-6650](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6650)

CASMPET-6650-csm-1.5

---

pb_node_images_application.yml
pb_node_images_compute.yml
pb_node_images_kubernetes.yml
pb_node_images_management.yml
pb_node_images_ncn-common.yml
roles/node_images_base/vars/packages/suse-aarch64.yml
roles/node_images_base/vars/packages/suse.yml
roles/node_images_hypervisor/vars/packages/suse.yml
roles/packages_csm/tasks/main.yml
roles/packages_csm/tasks/packages.yml
roles/packages_csm/vars/packages/suse.yml
roles/packages_csm/vars/services/suse.yml
roles/packages_user/tasks/main.yml
roles/packages_user/tasks/packages.yml
roles/packages_user/vars/packages/suse.yml
scripts/rpm-functions.sh
scripts/update-package-versions.sh

- Relates to: Hypervisor and VM work
The hypervisor and new VM images are pulling in node-images-base, which is installing several items that we do not want in those new images.
In an attempt to appease the new and current collection of images, this change breaks out the CSM packages and a curated list of user-space packages into their own, respective roles.
The CSM packages are now opt-in, as well as the user-space packages. This will significantly slim down the CVE footprint of our new images, while allowing us to have a common ground for all images. node-images-base now only contains a curated, bare-minimum set of packages. Each package in node-images-base also has its own rationale memo.
***NOTE*** Development within a booted hypervisor will be more difficult …

MTL-2189 Break out packages; mitigate CVEs in hypervisor

---

roles/node_images_management/vars/packages/suse.yml
roles/node_images_pre_install_toolkit/vars/packages/suse.yml

- Fixes: CASMINST-6625
Updates `pit-init` for CASMINST-6625.
Also pulls in new package names for pit-nexus and pit-observability.

CASMINST-6625 `pit-init`

---

roles/node_images_ncn_common/vars/packages/suse.yml

https://jira-pro.it.hpe.com:8443/browse/CASMCVT-229
- Fixes: fixes regarding the CDS have been included to CVT 
- Requires: new version built to be included
- Relates to:CVT (cvt-1.5.2-20230704071632_a2da8d744eec.x86_64.rpm)

CASMCVT-229 Adding latest CVT version 

---

roles/packages_csm/vars/packages/suse.yml

Use boto3 pagination api to fully list bucket contents.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6168
mug:
Before:
```
cray artifacts list thanos | grep ^Key | wc -l
1000
cray artifacts list velero | grep ^Key | wc -l
1000
```
After:
```
cray artifacts list thanos | grep ^Key | wc -l
1583
cray artifacts list velero | grep ^Key | wc -l
2913
```
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing

Change cray artifacts to return more than 1000 files (CASMPET-6168)

---

roles/node_images_ncn_common/vars/packages/suse.yml

This change adds new HMNFD Tavern tests to the HMS CT test wrapper. Previously only basic smoke tests were implemented but now additional functional tests are deployed during CT test runs. This change is targeting CSM-1.6.
* Partially resolves CASMHMS-3700.
New Tavern tests passing in GitHub actions. Also deployed updated tests on Dorian vShasta system running CSM-1.5.0-beta.10 and verified they passed.
Was an Upgrade tested? Y
Was a Downgrade tested? Y
Low risk, adds test coverage for HMNFD.

CASMHMS-3700 Bump hpe-csm-scripts to v0.6.0

---

roles/node_images_ncn_common/files/scripts/metal/metal-lib.sh
roles/packages_csm/vars/packages/suse.yml

Change how tenant name header is passed to also work with other headers.
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-6514
mug:
```
ncn-w004:~/.config/cray/configurations # cray uas create --publickey ~/.ssh/id_rsa.pub --format toml -vvvv
Loaded token: /root/.config/cray/tokens/api_gw_service_nmn_local.vers
REQUEST: POST to https://api-gw-service-nmn.local/apis/uas-mgr/v1/uas
OPTIONS: {'params': {'imagename': None, 'ports': None}, 'data': <MultipartEncoder: {'publickey': ('id_rsa.pub', <_io.BufferedReader name='/root/.ssh/id_rsa.pub'>)}>, 'headers': {'Content-Type': 'multipart/form-data; boundary=183efc470a9645c4af49e8b12f917d14', 'Cray-Tenant-Name': 'vcluster-blue'}, 'verify': False}
uai_age = "0m"
uai_connect_string = "ssh vers@10.102.162.162"
uai_host = "ncn-w006"
uai_img = …
```

Add tenant name header allowing other headers (CASMINST-6514)

---

roles/node_images_ncn_common/files/scripts/metal/metal-lib.sh

This reverts commit a23865eb8166ad7dcdb0b84064d4d4644d2c0fdb.

Revert "CASMINST-6532: Do not install cmstools on storage NCNs (#251)"

---

roles/node_images_base/vars/packages/suse.yml
roles/node_images_management/vars/packages/suse.yml

- Fixes: MTL-2179
`mkisofs` is needed for the cloud-init ISO generation by some VM tools such as `pulumi` and `virsh`.
Also adds `metal-init` and `libvirt` to the Management VM.

Adds more needed packages for management-vm

---

roles/node_images_base/vars/packages/suse.yml

- Fixes: MTL-2191
- Relates to: https://github.com/Cray-HPE/metal-provision/commit/d338583bb4f61e51ae55c57c548172cbfc6364a8
[SUSE-RU-2023:2240-1](https://www.suse.com/support/update/announcement/2023/suse-ru-20232240-1/) brought in a new systemd and udev flavor that contains the following patches:
1. [`0005-udev-create-default-symlinks-for-primary-cd_dvd-driv.patch`](https://build.opensuse.org/package/view_file/SUSE:SLE-15-SP4:Update/systemd/0005-udev-create-default-symlinks-for-primary-cd_dvd-driv.patch?expand=1)
1. [`1001-udev-use-lock-when-selecting-the-highest-priority-de.patch`](https://build.opensuse.org/package/view_file/SUSE:SLE-15-SP4:Update/systemd/1001-udev-use-lock-when-selecting-the-highest-priority-de.patch?expand=1)
The second patch, …

MTL-2191 1.5

---

roles/node_images_ncn_common/vars/packages/suse.yml

Enhance goss-k8s-pods-ips-in-nmn-pool.yaml test to attempt to find sls file on filesystem if sls not available, as well as use nmap to determine if IP is in subnet range.
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-6527
Drax:
```
ncn-m001:~/brad # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-pods-ips-in-nmn-pool-brad.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
..
Total Duration: 1.660s
Count: 2, Failed: 0, Skipped: 0
```
```
ncn-m001:~/brad # ./check_goss_k8s_pods_ips_in_nmn_pool.sh
Successfully called sls search networks...
PASS: All K8S pod IPs are in the NMN Bootstrap DNCP Subnet
```
```
ncn-m001:~/brad # ./check_goss_k8s_pods_ips_in_nmn_pool.sh
Failed to talk to sls, looking for sls_input_file.json …
```

Fix nmn pool test to attempt to find input file if sls not up yet (CASMINST-6527)

---

roles/node_images_ncn_common/vars/services/suse.yml

CASMTRIAGE-5681: enable csm-node-heartbeat service on NCNs

---

roles/packages_user/vars/packages/suse.yml

New base image bring in a newer mozilla-nss which is incompatible with the pinned libfreebl3.
Fixes: https://github.com/Cray-HPE/node-images/actions/runs/5576872000/jobs/10190668285#step:11:4370

Fix base image builds

---

roles/packages_user/vars/packages/suse.yml

Zypper is failing to install libfreebl3-hmac
https://github.com/Cray-HPE/node-images/actions/runs/5577879198/jobs/10191313968?pr=838#step:11:4275

libreebl3-hmac is obsolete

---

roles/packages_user/vars/packages/suse.yml

- Fixes: MTL-2205
Pins the:
- elf packages
- libldap packages
- and mozilla-nss packages
All of which have caused build issues for images or CSM. This pins the full set of packages to prevent Zypper from complaining, so the entire set is downgraded without conflicts.

MTL-2205 Pin troublesome packages

---

roles/node_images_ncn_kubernetes/vars/packages/suse.yml

Change cpu throttle detection script to not assume kubectl output order.
* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5697
Dorian:
```
ncn-m001:~ # /opt/cray/platform-utils/detect_cpu_throttling.sh nls
Checking cray-nls-678b49ffdb-wbnkd
*** CPU throttling for containerid a41c13afb6624a2edcd56c3212e73f67c51a668d84ed212252c06f32360ddf5e: ***
nr_periods 1167749
nr_throttled 307
throttled_time 4771194407
Checking cray-nls-argo-workflows-server-85d4d8866d-tkw54
*** CPU throttling for containerid c63c012d528a43f6a321cb5dcdf870fbd82f0eb8db8c61bdd1f2e08d56017718: ***
nr_periods 1124931
nr_throttled 1
throttled_time 2555416
Checking cray-nls-argo-workflows-workflow-controller-66fcbc9679-hwgkd
Checking cray-nls-postgres-0
*** CPU throttling for containerid …
```

Change cpu throttle script to be k8s version agnostic (CASMTRIAGE-5697)

---

roles/node_images_ncn_common/vars/packages/suse.yml

Add combined health check for use after CSM services are upgraded, but NCNs have not yet rolled by IUF management node rollout.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6670
Drax (one expected failure):
```
ncn-m003:~ # /opt/cray/tests/install/ncn/automated/ncn-k8s-combined-healthcheck-post-service-upgrade
NCN and Kubernetes Checks (post CSM services upgrade)
------------------------------
Writing full output to /opt/cray/tests/install/logs/print_goss_json_results/20230718_212313.352790-566853-ygO1buGe/out
Running tests
Checking test results
Only errors will be printed to the screen
Result: FAIL
Source: http://ncn-m001.hmn:9008/ncn-healthcheck-master-single-post-service-upgrade
Test Name: Check hmnfd service
Description: Performs a basic health check on the hmnfd service. If this …
```

Include post services install suite in ncn-k8s-combined-healthcheck (CASMPET-6670)

---

roles/node_images_storage_ceph/vars/packages/suse.yml

Fresh install changes for smartmon on storage nodes for CSM 1.5
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6687
Deployed rpm to craystack, installed rpm on mug and ran the apply successfully.
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing

Add smartmon configuration for node-exporter on storage nodes (CASMPET-6687)

---

roles/node_images_storage_ceph/vars/packages/suse.yml
roles/node_images_storage_ceph/vars/services/suse.yml

Fix conflicts and refactor smartmon rpm
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6687
```
ncn-s001:~/brad # ./install.sh
Loading repository data...
Reading installed packages...
Resolving package dependencies...
The following 5 NEW packages are going to be installed:
cephadm golang-github-prometheus-node_exporter libfmt8 ses-release smart-mon
The following NEW product is going to be installed:
"SUSE Enterprise Storage 7"
The following 5 packages have no support information from their vendor:
cephadm golang-github-prometheus-node_exporter libfmt8 ses-release smart-mon
5 new packages to install.
Overall download size: 96.8 KiB. Already cached: 8.6 MiB. After the operation, additional 19.4 MiB will be
used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving: …
```

Pin to better smart-mon rpm, enable and start the service (CASMTRIAGE-5697)

---

roles/node_images_ncn_common/vars/packages/suse.yml

CASMCVT-237
- Fixes: **Latest fixes have been included for CDS**
- Requires: **new version built to be included**
- Relates to: **cvt-1.5.5-20230721101203_155d6ad01475.x86_64.rpm**

latest cvt vers with bug fixes

---

roles/node_images_base/vars/packages/suse.yml

Fixes the`lts/csm-1.5` build for `node-images`

Upgrade openssh version for build fix.

---

roles/node_images_base/files/scripts/common/openscap.sh
roles/node_images_base/vars/packages/suse.yml

Updates the URL for OpenSCAP files to artifactory:
[MTL-2212](https://jira-pro.it.hpe.com:8443/browse/MTL-2212)
Bumps the OpenSSH version to fix the build:
[MTL-2211](https://jira-pro.it.hpe.com:8443/browse/MTL-2211)

OpenSCAP URL and OpenSSH Fix

---

roles/node_images_base/files/scripts/common/openscap.sh

Updates the URL for OpenSCAP files to artifactory:
[MTL-2212](https://jira-pro.it.hpe.com:8443/browse/MTL-2212)

OpenSCAP URL Frix

---

roles/node_images_base/vars/packages/suse.yml

- Relates to: MTL-2211 #240 #243 
The extra openssh packages were removed in https://github.com/Cray-HPE/metal-provision/pull/240/files#r1250894013 but these actually need to stay to mitigate pipeline failures when a new base image is built. New base images may have newer openssh dependencies installed, and Zypper will only bypass the prompt for downgrading them if every dependency is listed in the `zypper in` command.

MTL-2211 Repin remaining openssh packages

---

roles/node_images_ncn_common/vars/packages/suse.yml

- Fixes: [CASMHMS-6057](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6057)
The HMS REDS service is not needed and therefore does not run in vShasta. This change skips the REDS CT when we are executing in vShasta.
Executed the script to show that the REDS CT ran. Touched the /etc/google_system file and re-ran showing that the REDS CT was skipped. Removed /etc/google_system file and the REDS CT again executed.
No known risks

CASMHMS-6057  No reds CT in vShasta hpe-csm-scripts update

---

roles/node_images_ncn_common/vars/packages/suse.yml

- Fixes: [CASMHMS-6057](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6057)
The HMS REDS service is not needed and therefore does not run in vShasta. This change skips the REDS CT when we are executing in vShasta.
Executed the script to show that the REDS CT ran. Touched the /etc/google_system file and re-ran showing that the REDS CT was skipped. Removed /etc/google_system file and the REDS CT again executed.
No known risks

CASMHMS-6057 No reds CT in vShasta hpe-csm-scripts update

---

roles/node_images_management_vm/vars/packages/suse.yml
roles/node_images_pre_install_toolkit/vars/packages/suse.yml

Reverts Cray-HPE/metal-provision#331
Installing via cloud-init instead.

Revert "CASMINST-6578 cani add this rpm to the release"

---

roles/node_images_management_vm/vars/packages/suse.yml
roles/node_images_pre_install_toolkit/vars/packages/suse.yml

This reverts commit 18b6c381076533f8cce3bd81017571f9428ee5d1.
Installing via cloud-init instead.

Revert "CASMINST-6578 cani add this rpm to the release (#330)"

---

roles/node_images_base/vars/packages/suse.yml

add package:
-  dracut-mkinitrd-deprecated
dracut-mkinitrd-deprecated provides /sbin/mkinitrd which is required. I'll open a jira ticket to re-visit this and update code that depends on mkinitrd.

add dracut-mkinitrd-deprecated -- 1.5

---

roles/node_images_base/vars/packages/suse.yml

add package:
-  dracut-mkinitrd-deprecated
dracut-mkinitrd-deprecated provides /sbin/mkinitrd which is required. I'll open a jira ticket to re-visit this and update code that depends on mkinitrd.

add dracut-mkinitrd-deprecated

---

roles/node_images_hypervisor/files/management-vm/domain.xml
roles/node_images_hypervisor/files/management-vm/isolated.xml
roles/node_images_management_vm/files/cloud/cloud.cfg.d/00_network.cfg
roles/node_images_management_vm/files/cloud/templates/hosts.suse.tmpl

- Fixes: Isolated network added in #345 and #342 
1. `type="network"` was missing from the `<interface>` definition in `domain.xml`
2. wicked was rejecting DHCP leases on the link-local network, had to switch to something else (using Class C, private network)
Minor edits:
- Switched to `prefix` instead of `netmask` in `isolated.xml` because it's more human-readable.
- Updated `localhypervisor` entry in `/etc/hosts` for new IP range
- Reordered `<devices>` in `domain.xml` so the `<interface>` is on the bottom

Fix isolated network for hypervisor and management VM

---

roles/node_images_management_vm/vars/packages/suse.yml
roles/node_images_ncn_common/vars/packages/suse.yml
roles/node_images_ncn_kubernetes/vars/packages/suse.yml
roles/node_images_pre_install_toolkit/vars/packages/suse.yml
roles/packages_csm/vars/packages/suse.yml
scripts/repos/cray.template.repos

Removes the csm-rpms sle-15sp3 repository, and updates pins to fetch noos editions of RPMs previously pulled from that repository.
https://jira-pro.it.hpe.com:8443/browse/CASMINST-3431
- https://github.com/Cray-HPE/prodmgr/pull/20
- https://github.com/Cray-HPE/canu/pull/431
- https://github.com/Cray-HPE/craycli/pull/128
- https://github.com/Cray-HPE/manifestgen/pull/34
- https://github.com/Cray-HPE/hpe-csm-scripts/pull/58
- https://github.com/Cray-HPE/hpe-csm-scripts/pull/56
- https://github.com/Cray-HPE/hpe-csm-scripts/pull/57
- https://github.com/Cray-HPE/dracut-metal-dmk8s/pull/35
- https://github.com/Cray-HPE/dracut-metal-mdsquash/pull/60
- https://github.com/Cray-HPE/dracut-metal-luksetcd/pull/44
- https://github.com/Cray-HPE/cray-kubectl-hns-plugin/pull/3
- …

CASMINST-3431 Remove csm-rpms SP3

---

roles/node_images_application/tasks/main.yml

cloud-init config is handled by the `cloud_init` role, this task was supposed to go away but was neglected during that role's creation.

Task should be deleted

---

roles/node_images_application/vars/packages/suse.yml
roles/node_images_compute/vars/packages/suse.yml

The only part of https://github.com/Cray-HPE/csm/pull/2680 that still needed to make its way over to `metal-provision`

CASMCMS-8758: Update to noos bos-reporter RPM

---

roles/node_images_base/files/metal/dracut.conf.d/00-metal.conf

add `date` to our initrd. The cray-udev-network-cn rpm requires it.
- Fixes: Boot failure on stock sles compute images
Yes
None

add date to initrd

---

roles/node_images_ncn_common/files/scripts/metal/metal-lib.sh

CASMTRIAGE-5907: also search the csm-noos repo

---

roles/node_images_base/files/scripts/metal/create-iso-artifact.sh
roles/node_images_base/vars/packages/suse.yml
scripts/repos/suse.template.repos

- Fixes: MTL-2253
- Relates to: MTL-2192, CASMTRIAGE-5930 #298 
This pulls in PTF packages for `systemd` and `udev` and rolls back the previous MTL-2192 workaround. The new PTF packages fix the USB ISO boot, and reverting the workaround fixes the RemoteISO boot.
I successfully built a Fawkes ISO and tested it via USB and iLO BMC.
I did not test a pre-install-toolkit ISO, I couldn't get one to build. However all of our ISOs are built the same way, and tests I did were sufficient to say all of our ISOs work.

MTL-2253 `systemd` and `udev` PTF for Remote and USB ISO Boots

---

roles/node_images_hypervisor/files/systemd/ssh-import-id.service
roles/node_images_hypervisor/tasks/main.yml
roles/node_images_hypervisor/vars/services/suse.yml

- add ssh-import-id systemd service to pull public ssh key from management-vm
- add ssh-import-id systemd service in build pipeline and enable it
Yes
None known

MTL-2247-ssh-keys

---

roles/node_images_base/files/scripts/metal/create-kis-artifacts.sh

Remove character special files from the filesystem prior to creating the squashfs artifact.
- Fixes: CASMTRIAGE-5941

CASMTRIAGE-5941: remove character special files from filesystem 

---

roles/node_images_management_vm/vars/packages/suse.yml
roles/node_images_pre_install_toolkit/vars/packages/suse.yml

- Fixes: MTL-2254
Includes the new nexus 3.38.0-1 image, matching cray-nexus.
Also includes cray-nexus' current cray-setup-nexus image (0.10.1).

MTL-2254 Upgrade to nexus 3.38.0-1

---

scripts/packer/cleanup-functions.sh

The release file from #375 created a human friendly date stamp with the format of:
```
2023:08:28-13:30:24
```
I'd prefer not overusing the same delimiter, it's my belief that it's easier to understand the date string with:
```
2023-08-28_13:30:31
```

Use `+%Y-%m-%d_%H:%M:%S` for the release file

---

group_vars/application/packages.suse.yml
group_vars/compute/packages.suse.yml

Worker nodes on lemondrop were starting the cray-heartbeat with the wrong gateway address due to some virtio kernel modules that were loaded for qemu ARM builds. vShasta v2 uses the same gateway address that metal nodes do, so there is no need to differentiate between the two.
- Fixes:  [CASMHMS-6089](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6089)
- Requires:
- Relates to:
Fix for vShasta v2 API gateway.
On systems that do not have any virtio kernel modules loaded the default path through the script is unchanged.
No risks to metal installs.

CASMHMS-6089 Update node heartbeat to use same gateway for vShasta and metal

---

group_vars/application/services.suse.yml
group_vars/compute/services.suse.yml
group_vars/kubernetes/services.suse.yml
group_vars/storage_ceph/services.suse.yml

- Relates to: #375 
csm-node-heartbeat and csm-node-identity were disabled by default, and meant to be enabled per-group but the enablement never happened in #375.
This enables both services for application, compute, kubernetes, and storage-ceph nodes.

csm-node-heartbeat and csm-node-identity regress

---

roles/node_images_metal/files/scripts/metal/.gitignore
roles/node_images_metal/files/scripts/metal/create-iso-artifact.sh

- Fixes: CASMTRIAGE-5988
- Relates to: #375 
This fixes the `grub.cfg` file for the pre-install-toolkit.
- The `ISO_FSLABEL`'s default value, that the pre-install-toolkit relies on, had single-quotes added to it. This creates a malformed label: `LABEL='CRAYLIVE'`
```bash
ls -l /dev/disk/by-label/
total 0
lrwxrwxrwx 1 root root 10 Sep  1 15:35  BOOT -> ../../sdd2
lrwxrwxrwx 1 root root 11 Sep  1 15:35  BOOTRAID -> ../../md124
lrwxrwxrwx 1 root root 10 Sep  1 15:35  CRAYS3CACHE -> ../../dm-0
lrwxrwxrwx 1 root root  9 Sep  1 15:35  ETCDLVM -> ../../sdc
lrwxrwxrwx 1 root root 10 Sep  1 15:35  PITDATA -> ../../sdd4
lrwxrwxrwx 1 root root 11 Sep  1 15:35  ROOTRAID -> ../../md126
lrwxrwxrwx 1 root root 11 Sep  1 15:35  SQFSRAID -> ../../md125
lrwxrwxrwx 1 root root 10 Sep …
```

CASMTRIAGE-5988 pre-install-toolkit bad FSLabel

---

pb_node_images_management-vm.yml
roles/node_images_management_vm/tasks/main.yml

When templating, the `.j2` suffix must be removed.

Do not preserve `.j2` suffix

---

group_vars/management_vm/packages.suse.yml
group_vars/pre_install_toolkit/packages.suse.yml
roles/bootserver/templates/apache2/vhosts.d/vhosts.htaccess.j2
roles/node_images_pre_install_toolkit/files/apache2/nexus.conf

Nexus itself is being reconfigured to operate with a sub-path, all proxies must also redirect to the new sub-path running at localhost:8081/nexus.
For more context, see: https://github.com/Cray-HPE/metal-nexus/pull/23

Correct the nexus sub-path

---

group_vars/hypervisor/services.suse.yml

- enable ssh-import-id.service
https://jira-pro.it.hpe.com:8443/browse/MTL-2247
Yes
None

MTL-2247 partial

---

vars/packages/suse.x86_64.yml

ucode-intel is already included by default/dependency.
- Fixes: MTL-2256
- Relates to: zenbleed

MTL-2256: include ucode-amd

---

roles/node_images/files/scripts/common/openscap.sh

Our DST ARM runners don't have a new enough version of curl so we can't use **--retry-all-errors**. Switching out curl for wget.
Yes
None known

use wget instead of curl

---

group_vars/ncn_metal/packages.suse.yml

- Fixes: MTL-2273
- Relates to: MTL-2272

MTL-2273: add "defaults" xfs mount option

---

group_vars/storage_ceph/packages.suse.yml
scripts/repos/suse.template.repos
vars/packages/csm.suse.yml

Suse Storage/6 and Storage/7 repos are deprecated so we're going to stop using them.
Downgrading several packages and removing one.
python3-urllib3
python3-colorama
ses-release

remove Storage repos

---

roles/node_images_hypervisor/templates/systemd/ssh-import-id.service.j2

- append ssh keys instead of clobbering authorized_keys
- create /etc/ssh/ssh_import_id.disabled after successfully retrieving ssh keys from gitea
None known

ssh-import-id.service updates

---

scripts/nexus/setup-nexus.sh

- Relates to: [CASMTRIAGE-6017](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6017)
When setup-nexus script runs into error, it often fails silently. This PR makes the error bubble up, enabling the caller to be aware and handle the errors accordingly.
Low.

CASMTRIAGE-6017: fix setup-nexus script silent failure

---

group_vars/compute/packages.suse.yml
group_vars/kubernetes/packages.suse.yml
group_vars/ncn/packages.suse.yml

`metal-provision` CSM 1.6 PR for https://github.com/Cray-HPE/csm/pull/2842
I also added a commit for [CASMINST-6657](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6657) to address a couple of other RPM versions which are out of sync for what we should be using for CSM 1.6.

CASMINST-6654/CASMINST-6657: Make sure that test failures are logged when CMS Goss tests are unable to run; fix RPM versions

---

group_vars/ncn/packages.suse.yml

Update `goss-servers` RPM to add new test endpoint.

CASMINST-6658: Add Goss server endpoint for Kubernetes cluster tests

---

scripts/nexus/setup-nexus.sh

- Fixes: MTL-2278
False alarm.
The YUM repos are working, the 500 HTTP errors we encountered earlier were due to bad RPMs.

MTL-2278 This is not actually broken

---

group_vars/ncn/packages.suse.yml

https://github.com/Cray-HPE/csm/pull/2869

CASMINST-6663: Prevent Goss tests from failing due to missing environment variable

---

group_vars/pre_install_toolkit/packages.suse.yml

- Relates to: MTL-2000
Resolves queries to `packages.local` with the PIT nexus IP while dnsmasq is running.

MTL-2000 Point `packages.local` to pit-nexus during bootstrap

---

roles/node_images_management_vm/templates/cloud/templates/hosts.suse.tmpl.j2
scripts/repos/cray.template.repos

The `hosts.suse.tmpl.j2` file is rendering with a blank line at the top of file, this blank line is preventing the template from rendering its variables during cloud-init.
With the blank line, the rendered `/etc/hosts` still contains `{{fqdn}}` and `{{hostname}}`.
This ensures there's no leading blank line after the `{% raw %}` block start.
Also adds the nodes expected, isolated IP to the template.

`hosts.suse.tmpl.j2` is rendering incorrectly

---

group_vars/ncn/packages.suse.yml

- Fixes: CASMHMS-6072
Tested updated `run_hms_ct_tests.sh` for REDS removal and it worked. For testing see: https://github.com/Cray-HPE/hpe-csm-scripts/pull/60
No known issues.

CASMHMS-6072: Bump hpe-csm-scripts version

---

vars/packages/csm.suse.yml

CASMTRIAGE-6098: fix spire path for spire-agent

---

group_vars/kubernetes/packages.suse.yml
scripts/repos/cray.template.repos

The `cray-sat-podman` RPM has been moved from the sat-rpms repository in Artifactory to the csm-rpms repository. Its version has also been incremented from 2.0.0-1 to 2.1.0-1. Update the version of this package included in the Kubernetes NCN images, and remove the sat-rpms repository, which is no longer used for any RPMs included here.
- Fixes: CRAYSAT-1774
Unsure.
This should be low-risk. It doesn't change any functionality. As long as the images build, it should be okay.

CRAYSAT-1774: Update version of cray-sat-podman and remove sat-rpms repo

---

group_vars/pre_install_toolkit/packages.suse.yml

MTL-2296: we can't use >= 2.5.0 on CSM

---

roles/node_images_ncn/files/cloud.cfg
roles/node_images_ncn_metal/files/scripts/metal/install.sh
roles/node_images_ncn_metal/files/scripts/metal/metal-lib.sh

- Fixes: MTl-2000
Enables repository setup and package installation from cloud-init, using the zypper and packages cloud-init modules.
This deprecates and disables the package install hack (`install_csm_rpms`).
This change depends on the following cloud-init user-data existing:
```bash
ncn-m001:~ # cray bss bootparameters list --format json --hosts $(cat /etc/cray/xname) | jq '.[]."cloud-init"."user-data".packages'
[
"cani",
"canu",
"cray-cmstools-crayctldeploy",
"csm-testing",
"goss-servers",
"iuf-cli",
"libcsm",
"platform-utils"
]
```
```bash
ncn-m001:~ # cray bss bootparameters list --format json --hosts $(cat /etc/cray/xname) | jq '.[]."cloud-init"."user-data".zypper'
{
"repos": [
{
"autorefresh": 1,
"baseurl": …
```

MTL-2000 Enable zypper cloud-init modules

---

roles/bootserver/tasks/main.yml
roles/bootserver/templates/dnsmasq.conf.j2
roles/bootserver/templates/dnsmasq.d/boot.conf.j2
roles/grub/defaults/main.yml
roles/grub/tasks/main.yml

- Fixes: MTL-2237
- Relates to: #517 
To test this, I uploaded a tarball from https://github.com/Cray-HPE/fawkes/pull/15 and then PXE booting a hypervisor node on redbull.
Generated `grub.cfg` file:
```
#
#
#
#
#
#
---
gfxmode=auto
timeout=2
default=1
locale_dir=$prefix/grub.locale
lang=en_US
menuentry 'LiveCD' {
set gfxpayload=keep
echo 'Loading kernel ...'
linux (http,bootserver)/nexus/repository/fawkes-images/hypervisor/boot/x86_64/loader/kernel biosdevname=1 console=tty0 console=ttyS0,115200 crashkernel=360M iommu=pt ip=dhcp pcie_ports=native psi=1 rd.live.ram=1 rd.md.conf=0 rd.md=0 rd.neednet=1 rd.peerdns=1 rd.shell root=live:http://bootserver/nexus/repository/fawkes-images/hypervisor/hypervisor-6.1.37-x86_64.iso split_lock_detect=off …
```

MTL-2237 tarball updates

---

roles/node_images_ncn/files/systemd/metalfs.service

There is a race condition such that BOOTRAID exists, but /etc/fstab.metal might not exist until ~1 second after that. This caused the ExecCondition to fail.
- Fixes: MTL-2262

MTL-2262: ensure `fstab.metal` exists before trying to reference it

---

roles/node_images_ncn/files/cloud.cfg

- Fixes: CASMTRIAGE-6201
DNS is unreliably set up before `runcmd` is ran, and at scale (even with only 9 nodes) it is possible that the repo URLs do not resolve.
Move `zypper_add_repo` and `package_update_upgrade_install` from `init` to `final`. Ensuring it runs after `runcmd` runs.
Optionally we could've moved these to _before_ `bootcmd`, since `runcmd` invokes our `net-init.sh` script which in turn re-runs `cloud-init init`. `bootcmd` naturally fails on subsequent runs, so anything after `bootcmd` and before `cloud-init config` never get another shot. That means moving these _before_ `bootcmd` should have the same or better effect. We might go that route if we encounter another issue with this.

CASMTRIAGE-6201 (1.6)

---

group_vars/kubernetes/packages.suse.yml

Fix etcd cluster balance test to account for defrag pod (hbtd)
* CASMPET-6827: etcd cluster balance check needs to avoid defrag pods
mug:
```
ncn-m001:/mnt/developer/bklein # kubectl get po -n services | grep cray-hbtd-bitnami-etcd
cray-hbtd-bitnami-etcd-0                                          2/2     Running            352 (17h ago)      13d
cray-hbtd-bitnami-etcd-1                                          2/2     Running            361 (17h ago)      13d
cray-hbtd-bitnami-etcd-2                                          2/2     Running            2506 (17h ago)     13d
cray-hbtd-bitnami-etcd-snapshotter-28304220-8rdhn                 0/2     Completed          0                  38m
kube-etcd-defrag-cray-hbtd-bitnami-etcd-28304234-4t6ph            0/2     Completed          0 …
```

Update platform-utils to fix etcd cluster balance check (CASMPET-6827)

---

group_vars/kubernetes/packages.suse.yml

- Relates to: CRAYSAT-1771 and CRAYSAT-1767
Update the version of the cray-sat-podman RPM to 3.0.0 for CSM 1.6.0. This new version uses the new path to the cray-sat container image in Nexus where it is uploaded by CSM 1.6.0.
No changes to idempotency.
This new version of the `cray-sat-podman` will use a new default path in Nexus for the `cray-sat` container image, and the change that will upload the `cray-sat` container image to this new path is https://github.com/Cray-HPE/csm/pull/2962
This change is only intended for CSM 1.6.0. We should try to merge this PR at the same time as the aforementioned csm PR.
If we mess up the timing of these two PRs, the result will be that `sat` commands will complain about not being able to find the `cray-sat` container image. Such a …

CRAYSAT-1767: Update cray-sat-podman RPM version for CSM 1.6.0

---

group_vars/fawkes_live/packages.suse.yml
group_vars/hypervisor/packages.suse.yml
group_vars/pre_install_toolkit/packages.suse.yml

- Fixes:  https://jira-pro.it.hpe.com:8443/browse/CASMPET-6835
Changes kube-proxy-replacement to cilium-kube-proxy-replacement to match up with kubernetes-cloudinit.sh.
Built CSI binary locally and ran csi config init both with and without cilium-kube-proxy-replacement defined in system_config.yaml. Verified that the correct value was generated in data.json.

CASMPET-6835:  Change kube-proxy-replacement to cilium-kube-proxy-replacement in CSI

---

group_vars/ncn/packages.suse.yml
roles/node_images_ncn/files/utilities/common/craysys/metal.py

- Fixes: MTL-2346
- Relates to: #574 
Fixes `ModuleNotFoundError: No module named 'DataSourcenocloud-net` (https://github.com/canonical/cloud-init/issues/4302) by pulling in cloud-init 23.2.2.
Since we adopted cloud-init 22+ in #574, based on [this commit](https://github.com/Cray-HPE/node-images/commit/51dc8d48e9bb791e2f2f3e1d3dec0b4de0ab610b) we also need to remove line 43 from `craysys`' `metal.py`.

MTL-2346 `craysys` update for newer cloud-init

---

group_vars/ncn/packages.suse.yml

[CASMCVT-252](https://jira-pro.it.hpe.com:8443/browse/CASMCVT-252)
- Fixes: Latest fixes have been included for CVT and CDS
- Requires: new version built to be included
- Relates to: cvt-1.5.16-20231117084626_6a46ee25062e.x86_64.rpm

CASMCVT-252:adding latest vers of cvt

---

group_vars/ncn/packages.suse.yml

metal-provision CSM 1.5 PR for https://github.com/Cray-HPE/csm/pull/3070

CASMINST-6730: Add Goss test to verify that all Kubernetes NCNs are at the same level

---

group_vars/management_vm/packages.suse.yml
group_vars/pre_install_toolkit/packages.suse.yml

- Fixes: MTL-2351 MTL-2352
MTL-2351 adds broadcom support to CSM 1.5 and CSM 1.6 for fresh installs.
MTL-2352 is a minor update that fixes a compilation error for ipxe with binutils 2.41, but as far as fawkes is concerned there's no functional change.

MTL-2351 and MTL-2352

---

group_vars/hypervisor/packages.suse.yml
vars/packages/libvirt.suse.yml

Install qemu when installing libvirt in order to work around https://github.com/Cray-HPE/node-images/actions/runs/7200009942/job/19613032823?pr=1029#step:10:3748
Libvirt is finding newer dependencies, that do not align with the designated qemu version. By installing qemu at the same time as libvirt, Zypper will ensure it pulls matching dependencies in.
This also updates qemu to the newer version.

Fix qemu dependency

---

group_vars/compute/packages.suse.yml
vars/packages/csm.suse.yml

- Fixes: [CASMHMS-6116](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6116)
Starlord's management nodes are not properly sending heartbeats because spire filtering is turned On. The csm-node-heartbeat RPM installed is version 2.4. This is incorrect for a CSM 1.5 system. We need to use the 2.5 version of the RPM because it contains both the spire path change and heartbeat URL change required for node to properly heartbeat when spire filtering is On.
- [] I tested this on a vshasta system or this pertains to the node-images pipeline (if yes and not build related, please include results or a description of the test)
Manually deployed the updated csm-node-heartbeat.sh file onto nid 18 and restarted csm-node-heartbeat service, resulting service status included the xname …

CASMHMS-6116 wrong csm node heartbeat

---

group_vars/management_vm/packages.suse.yml

`pdsh` is useful for ad-hoc commands to multiple servers.

Add `pdsh` to the fawkes management VM

---

group_vars/hypervisor/networks.yml
roles/network_manager/tasks/main.yml

I ran through another Fawkes install using the latest images (from before break) and I hit one problem with the `network_manager` role.
I included an amendment for a task name as well.

Fawkes runthrough bugfixes and tweaks

---

roles/node_images_pre_install_toolkit/files/apache2/nexus.conf
scripts/nexus/setup-nexus.sh

- Fixes: CASMINST-6766
- Relates to: fa3a066046a48896e02017ab57350989f0621ae5
This resolves extraneous errors observed during the updating of the Docker registry on the PIT.
During a fresh install, `setup-nexus.sh` is invoked in order to create/update repositories in Nexus before uploading tarball assets to them. CASMINST-6766 observed an error during the update of the Docker registry, this error is non-fatal, but does cause alarm. The result is the registry's meta fails to update, despite Docker images uploading successfully.
The failure was isolated to be due to a misconfiguration of the Apache2 proxy for nexus, in which some requests fail to route properly.
For example, the failing request in `setup-nexus.sh` was relying on the proxy, in the snippet below we see …

CASMINST-6766 Remediate extraneous errors observed during `setup-nexus` when updating the Docker registry

---

group_vars/ncn_metal/packages.suse.yml

MTL-2363: fix "one one" typo

---

group_vars/all.yml
scripts/repos/suse.template.repos
vars/packages/suse.x86_64.yml

- Fixes: MTL-2350
Includes a new Marvell/QLogic driver that addresses failed NIC recovery, the new driver allows a NIC to resume normal operations following a firmware stall.

MTL-2350 New Marvell/QLogic driver

---

roles/node_images_pre_install_toolkit/files/apache2/nexus.conf

- Fixes: MTL-2368
- Relates to: #604 #605 
The conditional from [`pitnode_bootstrap.sh`](https://github.com/Cray-HPE/livecd-gcp-infrastructure/blob/7668e6814671e5b76218ab3b8c7a840372c91874/scripts/pitnode_bootstrap.sh#L481) for clobbering `nexus.conf` is evaluating to True, and causing a regression of CASMINST-6766.
This PR restores the text that #604 and #605 needlessly removed.

MTL-2368 Fix conditional text for vshastav2

---

roles/node_images/tasks/main.yml
roles/node_images/templates/dracut.conf.d/01-blacklist.conf.j2
roles/node_images_metal/files/dracut.conf.d/00-metal.conf

- Fixes: MTL-2350
- Relates to: #611 #612 
PRs #611 and #612 blacklisted `qedr`, but it did not blacklist it from the initrd. This PR ensures that `qedr` is always omitted.
Additionally, this ensures that the other modules we want to blacklist aren't included in the initrd. Making our overall blacklisting _cleaner_, matching our hack for (1.2 or 1.3?) where we omitted modules on the NCN's cmdline.

MTL-2350 Ensure `qedr` is blacklisted everywhere

---

Jenkinsfile.github

Missed this in https://github.com/Cray-HPE/metal-provision/pull/619
Update Jenkinsfile to validate packages for aarch64 fawkes images.

update Jenkinsfile for fawkes arm package validation

---

roles/node_images_ncn_metal/files/scripts/metal/cleanup-live-images.sh

This script was refactored a while ago to account for the overlayFS, and in doing so many variable names were expanded to include `^SQUASHFS` or `^OVERLAYFS`. One variable was missed, `${BASE}`, for remounting the squashFS file.

Fix bad variable `${BASE}`

---

group_vars/compute/services.suse.yml
roles/node_images_metal/files/scripts/metal/create-kis-artifacts.sh
roles/node_images_metal/files/scripts/metal/grub.template.cfg
roles/node_images_ncn_metal/files/scripts/metal/metal-lib.sh

- replace linuxefi with linux in the grub config
- replace initrdefi with initrd in the grub config
- remove UUID mounts from /etc/fstab for kis and iso artifacts
- disable unecessary COS services in the stock sles compute image

CASMTRIAGE-6598++ -- 1.6

---

group_vars/compute/packages.suse.yml
vars/packages/csm.suse.yml

metal-provision PR for https://github.com/Cray-HPE/csm/pull/3165

CASMCMS-8905: Removed unintended ability to update all BOS v2 session fields

---

group_vars/ncn/packages.suse.yml
scripts/repos/cray.template.repos

- remove sma-cli-utils
None known. sma-cli-utils is now installed via cloud-init.

remove sma-cli-utils -- 1.6

---

scripts/packer/cleanup-functions.sh
scripts/packer/setup-functions.sh

Create the release file early in the build so that 3rd party RPMs can use it to determine node type. The SDU team will be leveraging this.  The bulk of the code change will be in a node-images PR.
- Fixes: MTL-2282

MTL-2282: create /etc/$NAME-release earlier in the build

---

vars/packages/csm.suse.yml

[CASM-4349](https://jira-pro.its.hpecorp.net:8443/browse/CASM-4349)
This is adding the api calls to the cray cli for IMS to interact with remote build nodes. 
This has no impact on anything except the new ims api in craycli. If this is installed on an older system without the update IMS api, all old api's still work exactly as they always have. If the new IMS is installed, but the new cray cli isn't everything will work, but the users will not be able to set remote build nodes through the cray cli. 
This has very little risk - only updating the cray cli version and that is detailed above.

CASM-4349 - add support for IMS remote build nodes.

---

scripts/repos/google.template.repos

- add temporary repo for k8s packages
https://jira-pro.it.hpe.com:8443/browse/MTL-2382
none

MTL-2382 -- 1.6

---

scripts/repos/google.template.repos

This reverts commit f2bba0df6db14e23b489a752319177fa12cac103.
google-packages-tmp is no longer needed.
https://cray.slack.com/archives/G01AJCLN36W/p1710451528430629?thread_ts=1710449746.271669&cid=G01AJCLN36W
NOTE: google-packages-mirror is no longer a mirror of google's rpm repository, as google stopped providing that repository.
google-packages-mirror is now a local artifactoryrepo containing only the packges we need.
none

Revert "temporary repo for k8s packages"

---

scripts/repos/google.template.repos

This reverts commit c87dbb8f1bee0b0e01a9eed7363f876ba943077b.
google-packages-tmp is no longer needed.
https://cray.slack.com/archives/G01AJCLN36W/p1710451528430629?thread_ts=1710449746.271669&cid=G01AJCLN36W
NOTE: google-packages-mirror is no longer a mirror of google's rpm repository, as google stopped providing that repository.
google-packages-mirror is now a local artifactoryrepo containing only the packges we need.
none

Revert "temporary repo for k8s packages" -- 1.5

---

group_vars/pre_install_toolkit/packages.suse.yml
scripts/nexus/setup-nexus.sh

Make 2 changes required to support copying container images together with Sigstore attachments:
- Upgrade metal-nexus to 3.67.1
- Use vendored version of skope-sync function in setup-nexus.sh, which implies --all CLI option requred for signature passing along with images. Vendored version also implies --retry-times, so dedicated function scope-sync-with-retry is not needed anymore.
- Relates to: CASM-4669
Please refer to testing description for https://github.com/Cray-HPE/metal-nexus/pull/25 
This introduces some risk since this change also brings in a newer version of Nexus, but otherwise a new functionality required by CSM 1.6 roadmap can not be achieved.

CASM-4669 Support container image signatures

---

roles/network_manager/defaults/main.yml
roles/network_manager/tasks/main.yml

For service endpoints that live in the management VM, we need to ignore the returned IP and force it to resolve over the isolated network.
```bash
TASK [network_manager : Configure DNS on the local hypervisor] *******************************************************************************************************************************************************************
ok: [hypervisor.local]
TASK [network_manager : Configure DNS overrides on the local hypervisor] *********************************************************************************************************************************************************
changed: [hypervisor.local] => (item=bootserver)
changed: [hypervisor.local] => (item=fawkes)
changed: [hypervisor.local] => (item=packages)
changed: …
```

Add `.mtl` overrides for the local hypervisor

---

group_vars/fawkes_live/packages.suse.yml
group_vars/fawkes_live/services.suse.yml
group_vars/hypervisor/packages.suse.yml
group_vars/hypervisor/services.suse.yml
group_vars/management_vm/packages.suse.yml
group_vars/management_vm/services.suse.yml

- Fixes: MTL-2300
- Requires: https://github.com/Cray-HPE/crucible/pull/46
New crucible package featuring a systemd daemon for auto-updating the crucible RPM from nexus.
Enables the `crucible-update.service` on hypervisor nodes; disabled in fawkes-live and the management-vm.

MTL-2300 New crucible

---

group_vars/compute/packages.suse.yml

- Fixes: [CASMCMS-8997](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8997)
- Fixes: [CASMCMS-8998](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8998)
Once this PR merges, I'll update my CSM manifest PR:
https://github.com/Cray-HPE/csm/pull/3394
Improvements to BOS v2 logging and additions of checks to prevent unnecessary API calls

CASMCMS-8997/CASMCMS-8998: BOS v2 fixes/improvements

---

group_vars/fawkes_live/packages.suse.yml
group_vars/fawkes_live/services.suse.yml
group_vars/hypervisor/packages.suse.yml
group_vars/hypervisor/services.suse.yml
group_vars/kubernetes_vm/packages.suse.yml
group_vars/kubernetes_vm/services.suse.yml
group_vars/management_vm/packages.suse.yml
group_vars/management_vm/services.suse.yml
group_vars/ncn/packages.suse.yml
vars/packages/csm.suse.yml
vars/packages/suse.aarch64.yml
vars/services/csm.suse.yml

- Fixes: CASMTRIAGE-6991 CASMPET-7058
Relates to: 
- https://github.com/Cray-HPE/csm-testing/pull/585
- https://github.com/Cray-HPE/csm-testing/pull/588

CASMTRIAGE-6991 `goss-servers.service` and CASMPET-7058 vShasta DNSMasq Test Fix

---

group_vars/fawkes_live/packages.suse.yml
group_vars/hypervisor/packages.suse.yml
group_vars/kubernetes_vm/packages.suse.yml
group_vars/management_vm/packages.suse.yml
group_vars/ncn/packages.suse.yml
vars/packages/csm.suse.yml

Package `goss-servers` now requires `goss`.
This will fix the missing `goss` binary we hit after the removal of the explicit `goss` callout: https://github.com/Cray-HPE/node-images/actions/runs/9195551941/job/25291695566#step:9:12814

MTL-2393 Fixed `goss-servers` deps

---

scripts/nexus/setup-nexus.sh

- Fixes: MTL-2407
Fixes several opportunities for `curl` to fail silently.
Cleans up output.
A message is logged to `stdout` when Kubernetes credentials are sourced for Nexus credentials.
The Kubernetes secret name for resolving Nexus credentials can now be overridden.
Ran `shfmt`.

MTL-2407 Fix silent `curl` errors in `setup-nexus.sh`

---

roles/node_images_metal/files/dracut.conf.d/00-metal.conf
roles/node_images_metal/files/scripts/metal/create-kis-artifacts.sh
vars/packages/suse.yml

- Fixes: MTL-2414
- Relates to: CAST-27383
Customer has requested that both the kdump and normal initrds for NCNs include more debugging binaries as well as the squashFS kernel module.
While the squashfs kernel module was present in our main initrd, it was not present in the kdump initrd.
This change adds the requested items to our dracut configuration, forcing both `dracut` and `mkdumprd` to include them.
New items:
- `squashfs.ko` (kdump initrd)
- `dmidecode`
- `gzip`
- `lsof`
- `lspci`
- `lsscsi`
- `md5sum`
- `netcat`
- `tar`
- `vim`
- `xz`
NOTE: In order to include `netcat`, the `netcat-openbsd` was needed. This package was added to all node-images via `vars/packages/suse.yml`.
Lastly, the customer requested `lib4_decompress.ko` for the sake of it being a dependency …

MTL-2414 initrd and kdump initrd additions

---

group_vars/management_vm/packages.suse.yml
group_vars/pre_install_toolkit/packages.suse.yml

New metal-ipxe for Fawkes and CSM:
- Fawkes: metal-ipxe-2.6.0
- CSM: metal-ipxe-2.4.100
Includes updated iPXE source: https://github.com/Cray-HPE/ipxe/pull/11
Includes missing Cray HTTPs/EFI+ACPI code: https://github.com/Cray-HPE/ipxe/pull/12

MTL-2104 CASMCMS-9041

---

group_vars/compute/packages.suse.yml
vars/packages/csm.suse.yml

- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9052
- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7147
CASMCMS-9052: This updates the BOS reporter RPM to a version which has API request timeouts added.
CASMTRIAGE-7147: Updates the Cray CLI to support the new BOS max_component_batch_size option.

CASMCMS-9052/CASMTRIAGE-7147: Update BOS reporter and Cray CLI

---

roles/node_images/files/scripts/common/openscap.sh

The aggregate sles15 openscap files are too large and cause memory OOM issues during builds. Every time we run into an OOM we have to bump Packer's VM memory.
Instead of downloading a 279M and 395M file for openscap, we can download the smaller 4M and 9M files for the service pack.
```
suse.linux.enterprise.server.15-patch.xml          23-Jul-2024 03:33    279M
suse.linux.enterprise.server.15-patch.xml.bz2      23-Jul-2024 03:33     24M
suse.linux.enterprise.server.15-patch.xml.gz       23-Jul-2024 03:33     41M
suse.linux.enterprise.server.15.xml                23-Jul-2024 03:36    395M
suse.linux.enterprise.server.15.xml.bz2            23-Jul-2024 03:36     10M
suse.linux.enterprise.server.15.xml.gz             23-Jul-2024 03:36     20M
```
vs.
```
suse.linux.enterprise.15-sp6-patch.xml …
```

MTL-2432 Fix OOM issues when running openscap

---

roles/sysctl/files/sysctl.d/99-inotify.conf

- Fixes: [CASMTRIAGE-7151](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7151)
Increase the following two sysctl value to prevent `istio-proxy` failing to start with a `too many open files` error.
```
fs.inotify.max_user_watches=1048576
fs.inotify.max_user_instances=1024
```

CASMTRIAGE-7151 - istio-proxy is failing to start with too many open files

---

group_vars/compute/packages.suse.yml
vars/packages/csm.suse.yml

CASMCMS-9067 adds a new BOS v2 option. It resulted in a new RPM version for BOS reporter and the Cray CLI. This updates those RPMs. Once this merges, I'll make the corresponding `node-images` PR, and then the CSM manifest PRs.
- Relates to: [CASMCMS-9067](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9067)

CASMCMS-9067: Update BOS reporter and Cray CLI
