- roles/ncn-common-setup/files/srv/cray/scripts/metal/metal-lib.sh
Canu recently moved from the sp2 repo to the sp3 repo. This script
was not searching the sp3 repo. This commit rectifies the situation.
- Fixes: CASMINST-4791
> CASMINST-4791: search sp3 repo in addition to sp2

- roles/ncn-common-setup/files/srv/cray/scripts/common/create-kdump-artifacts.sh
Include last minute comment from docs-csm.
> Incorporate comments from reviewers in docs-csm

- roles/ncn-common/files/tests/common/ncn-common-tests.yml
- Relates to: MTL-1905
Only 1 kernel should be installed.
> MTL-1905 Add test for single-kernel

- roles/ncn-common/files/tests/common/ncn-common-tests.yml
> MTL-1905 Fix missing quote

- roles/ncn-common/files/scripts/common/create-ims-initrd.sh
add missing lib source; remove redundant --add
- Fixes: MTL-1923
> MTL-1923: add missing lib source; remove redundant --add

- roles/ncn-common/tasks/google.yml
- Fixes: VSHA-468
Follow-up to #41
> VSHA-468 Delete offending `cronjob`

- roles/ncn-common/files/sysctl/common/99-cray-ncn-network-common.conf
- roles/ncn-common/files/sysctl/google/99-google-network-common.conf
- roles/ncn-common/files/sysctl/metal/99-metal-ncn-common.conf
- roles/ncn-common/files/sysctl/metal/991-sma-ldms.conf
Reverts Cray-HPE/metal-provision#50
> Revert "Revert "MTL-1974 Cleanup `sysctl` settings""

- roles/ncn-common/files/scripts/metal/cleanup-live-images.sh
- Relates to: MTL-1871
This now will include overlayFS if `-o` is provided. The usage is also built out to be more descriptive.
> MTL-1871 Better usage and include overlayFS

- roles/ncn-common-cos/vars/common.yml
- roles/ncn-common/vars/vagrant.yml
This reverts commit 968bc056524c605311d165d890abcf8cd4bda8de.
Pulling cray-heartbeat back in.
> Revert "MTL-1708 Remove `cray-heartbeat` (#57)"

- roles/node-images-base/files/scripts/common/dracut-lib.sh
- Relates to: CASMTRIAGE-4697
The current logic here breaks when a TEST or PTF kernel is used. When using a TEST or PTF kernel, the kernel version and release are significantly different. The current logic produced a value for `KVER` that doesn't resolve in `/lib/modules/`:
```bash
ncn-w002:~ # . /srv/cray/scripts/common/dracut-lib.sh
ncn-w002:~ # echo $KVER
5.14.21-150400.24.33.2.25378.1.TEST-default
ncn-w002:~ # ls -l /lib/modules/$KVER
ls: cannot access '/lib/modules/5.14.21-150400.24.33.2.25378.1.TEST-default': No such file or directory
```
The `/lib/modules/$dir` is named differently:
```bash
ncn-w002:~ # ls -ld /lib/modules/5.14.21-150400.24.33.2.25378.1.TEST.1204911-default/
drwxr-xr-x 5 root root 439 Dec 22 01:31 …
```
> CASMTRIAGE-4697 Handle PTF/TEST Kernels

- pb_compute.yml
- roles/compute/defaults/main.yml
- roles/compute/tasks/common.yml
- roles/compute/tasks/google.yml
- roles/compute/tasks/main.yml
- roles/compute/tasks/metal.yml
- roles/compute/tasks/vagrant.yml
- roles/compute/vars/common.yml
- roles/compute/vars/google.yml
- roles/compute/vars/metal.yml
- roles/compute/vars/vagrant.yml
- Relates to: [MTL-2046](https://jira-pro.its.hpecorp.net:8443/browse/MTL-2046)
This PR adds a role for compute nodes
> MTL-2046: Add compute role

- roles/node-images-base/files/scripts/common/openscap.sh
- Fixes: MTL-2067
Download the `.xml` files into a temporary directory.
Resolve the SLES version via `/etc/os-release` to remove hardcode for `15`.
> MTL-2067 Cleanup `.xml` files

- roles/ncn-common/files/scripts/metal/metal-lib.sh
> CASMINST-5865: add iuf-cli to the list of rpms installed during cloud-init

- scripts/packer/cleanup-functions.sh
- scripts/packer/setup-functions.sh
- Relates to: #83 
Some changes made it into the `vendor/` directory instead of the metal-provision repo
Follow-up PR to #83.
> CASMINST-4571 pt3

- roles/node-images-compute/vars/packages/suse-x86_64.yml
- Fixes: (See notes below)
This updates BOS to 2.1.1.
[csm manifest PR](https://github.com/Cray-HPE/csm/pull/2151)
This resolves the following issues:
- CASMCMS-8560: Updated API spec for GET to `/` to reflect that it returns a list of versions
- CASMCMS-8570: Updated API spec for POST to `/v1/sessiontemplate` to reflect actual success status code (201)
- CASMCMS-8571: Ensure that DELETE requests to `/v1/sessiontemplate/{session_template_id}` return a meaningful status code
- CASMCMS-8573: Updated API spec for POST to `/v1/session` to include possible 404 status response
- CASMCMS-8574: Updated API spec for POST to `/v1/session` to reflect actual success status code (201)
- CASMCMS-8578: Updated API spec for POST to …
> BOS Update

- roles/node-images-hypervisor/vars/packages/suse.yml
- scripts/repos/suse.template.repos
Install `frr` into the hypervisor image.
This also adds the openSUSE SLE builds for `frr`, because the SLES repos only offer `frr-7`. The openSUSE repo builds `frr-8` for SLE15.4 and SLE15.5.
> CASM-4033 Hypervisor wants free range routing

- roles/node-images-pre-install-toolkit/vars/packages/suse.yml
https://github.com/Cray-HPE/pit-init/pull/68
> MTL-2141 New `pit-init`

- roles/node-images-ncn-common/vars/packages/suse.yml
https://github.com/Cray-HPE/csm-testing/pull/491
> CASMINST-6306 new goss-servers

- roles/node_images_base/vars/packages/suse.yml
- Fixes: fixes failed install of older curl version
> upgrade curl

- roles/node_images_ncn_common/vars/packages/suse.yml
- Fixes:
- Requires:
- Relates to:
> CASMCVT-193 add the signed CVT RPM

- scripts/nexus/setup-nexus.sh
- Relates to: #83 MTL-2032
Set script executable bit.
Include repository priorities, making the experience of using Nexus match that of our build pipeline (same behavior for resolving packages).
Fix Zypper prompts for repos using GPG check, Nexus does not have the GPG keys so disable GPG check on everything for now.
Tested on redbull:
```bash
cd /srv/cray/metal-provision/scripts/nexus
export ARTIFACTORY_USER=
export ARTIFACTORY_TOKEN=
export NEXUS_USERNAME=
export NEXUS_PASSWORD=
./setup-nexus -p
```
`zypper refresh` worked without prompts.
> MTL-2032 Update `setup-nexus.sh`

- roles/node_images_hypervisor/vars/packages/suse.yml
- scripts/rpm-functions.sh
Needed by mercury PoC items, helpful for running PoC
https://cray.slack.com/archives/CPVNL0RUM/p1684866122792659?thread_ts=1684861895.605859&cid=CPVNL0RUM
> Add more packages

- roles/node_images_base/vars/packages/suse.yml
- Fixes: CASMINST-6387
https://github.com/Cray-HPE/craycli/pull/104
> CASMINST-6387 Fix `craycli`

- roles/node_images_pre_install_toolkit/vars/packages/suse.yml
- Relates to: #151 
Necessary apache2 config update for MTL-2032.
> MTL-2032 New `default-server.conf`

- roles/node_images_pre_install_toolkit/defaults/main.yml
- roles/node_images_pre_install_toolkit/tasks/main.yml
> MTL-2032 Missed including loop var

- roles/node_images_pre_install_toolkit/tasks/main.yml
> Typo from copy-paste

- roles/node_images_base/vars/packages/suse.yml
- roles/node_images_pre_install_toolkit/vars/packages/suse.yml
> CASMINST-6418: bump pit-init version

- roles/node_images_pre_install_toolkit/vars/packages/suse.yml
- scripts/repos/cray.template.repos
Reverts Cray-HPE/metal-provision#167
> Revert "MTL-2165 and CASMINST-6333"

- roles/node_images_cos_ncn/vars/services/suse.yml
> CASMTRIAGE-5480: ensure cfs-state-reporter is enabled and started

- roles/node_images_cos_ncn/vars/services/suse.yml
> CASMTRIAGE-5480: don't start cfs-state-reporter

- scripts/repos/cray.template.repos
Minor update to align the repo name in this file with `main`.
> Rename repo to match main for a smaller diff

- roles/node_images_base/vars/packages/suse.yml
- another another google-guest-agent version update
> google-guest-agent version

- roles/node_images_base/tasks/metal.yml
- Fixes: CASMINST-6472
Remove `90-google.conf` to mitigate the large console log spam.
> CASMINST-6472 Fix log spam

- roles/node_images_hypervisor/vars/packages/suse.yml
https://cray.slack.com/archives/CPVNL0RUM/p1686690969986329?thread_ts=1686690420.295159&cid=CPVNL0RUM
> Hypervisor: Need libxslt-tools

- roles/node_images_ncn_common/vars/packages/suse.yml
- Fixes:
- Requires:
- Relates to:
> CASMCVT-206 Add cm cli RPM to kubernetes squashfs image

- roles/node_images_pre_install_toolkit/vars/packages/suse.yml
> MTL-2168 New `metal-ipxe`

- roles/node_images_base/vars/packages/suse.yml
- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8624
No risk change is backwards compatible.
> Updating craycli to 0.82.2

- roles/node_images_pre_install_toolkit/files/apache2/nexus.conf
- scripts/nexus/nexus-ssl.conf
- scripts/nexus/setup-nexus.sh
> MTL-2032 fixes 1.5

- roles/node_images_base/vars/packages/suse.yml
> CASMCMS-8624 stable

- roles/node_images_base/vars/packages/suse.yml
> CASMTRIAGE-5555: newer craycli

- roles/node_images_compute/vars/packages/suse.yml
https://github.com/Cray-HPE/csm/pull/2407
> CASMCMS-8676/CASMCMS-8674/CASMCMS-8649/CASMCMS-8532/CASMCMS-8661/CASMCMS-8667: BOS fixes and improvements

- scripts/nexus/setup-nexus.sh
> MTL-2032 Fix typo

- roles/node_images_base/files/scripts/common/openscap.sh
- roles/node_images_compute/vars/packages/suse.yml
- roles/node_images_pre_install_toolkit/vars/packages/suse.yml
- scripts/packer/setup-functions.sh
- add download retries for curl, pip
- update metal-ipxe and acpid rpm versions
Yes
None
> dl retries and package updates

- roles/node_images_ncn_common/vars/packages/suse.yml
- scripts/repos/cray.template.repos
- Fixes:
- Requires:
- Relates to:
> CASMCVT-226 Add latest noos CVT and cm-cli RPM

- scripts/nexus/setup-nexus.sh
- Relates to: CASMINST-5109
Add support for uploading an extracted `csm-suppelemental.tar.gz` into nexus.
Tested on ncn-m002 on redbull, vetting this does not need to run on the pit.
```bash
ncn-m002:/tmp/csm-supplemental # /srv/cray/metal-provision/scripts/nexus/setup-nexus.sh -s -r /tmp/csm-supplemental
Missing NEXUS_URL, presuming default: DEFAULT_NEXUS_URL
Error from server (NotFound): namespaces "nexus" not found
Unable to resolve NEXUS_USERNAME and NEXUS_PASSWORD from Kubernetes secret, assuming default ..
Uploading RPMs from /rpms ...
No apache2 proxy necessary, this is not a pit node.
Creating repo 'csm-supplemental-noos' ... Done
Uploading /tmp/csm-supplemental/repos/noos to csm-supplemental-noos ... Done
Creating repo 'csm-supplemental-sle-15sp4' ... Done …
```
> CASMINST-5109 CSM Supplemental support

- roles/node_images_application/vars/packages/suse-x86_64.yml
- roles/node_images_application/vars/packages/suse.yml
- roles/node_images_compute/vars/packages/suse-x86_64.yml
- roles/node_images_compute/vars/packages/suse.yml
- roles/node_images_ncn_common/vars/packages/suse.yml
> Add CMS SLES15SP5 noarch RPMs for Arm computes

- roles/node_images_pre_install_toolkit/vars/packages/suse.yml
- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASM-4366
Wasp
> CASM-4366: Upgrade pit-observability images (Grafana and prometheus) to the latest version

- management.yml
- pb_node_images_management.yml
- roles/node_images_management/tasks/main.yml
- roles/node_images_management/tasks/packages.yml
- roles/node_images_management/tasks/services.yml
- roles/node_images_management/vars/packages/suse.yml
- roles/node_images_management/vars/services/suse.yml
Adds a management role for the management VM.
> MTL-2176: Add management role

- management.yml
- pb_node_images_management.yml
- roles/node_images_management/tasks/main.yml
- roles/node_images_management/tasks/packages.yml
- roles/node_images_management/tasks/services.yml
- roles/node_images_management/vars/packages/suse.yml
- roles/node_images_management/vars/services/suse.yml
> Management vm stable

- pb_node_images_application.yml
- pb_node_images_compute.yml
- pb_node_images_management.yml
- pb_node_images_ncn-common.yml
- roles/node_images_base/vars/packages/suse-aarch64.yml
- roles/node_images_base/vars/packages/suse.yml
- roles/node_images_hypervisor/vars/packages/suse.yml
- roles/packages_csm/tasks/main.yml
- roles/packages_csm/tasks/packages.yml
- roles/packages_csm/vars/packages/suse.yml
- roles/packages_csm/vars/services/suse.yml
- roles/packages_user/tasks/main.yml
- roles/packages_user/tasks/packages.yml
- roles/packages_user/vars/packages/suse.yml
- scripts/rpm-functions.sh
> MTL-2189 Break out packages; mitigate CVEs in hypervisor (#240)

- roles/node_images_ncn_common/vars/packages/suse.yml
https://github.com/Cray-HPE/csm/pull/2510
> CASMTRIAGE-5630: Split iPXE check into two tests; modify suites to run appropriate iPXE check

- roles/node_images_hypervisor/vars/packages/suse.yml
- Relates to: #243
`virt-install` and `cloud-init` bring in some CVEs for `python3-requests`. Since we aren't sure whether we want these or not yet, it's best to just remove them for now.
> MTL-2189 Remove more CVE Influences

- Jenkinsfile.github
- roles/node_images_management/vars/packages/suse.yml
Adds `pulumi` to the management VM.
> MTL-2179 Add pulumi to the management VM

- Jenkinsfile.github
- roles/node_images_management/vars/packages/suse.yml
- roles/node_images_ncn_common/vars/packages/suse.yml
> CASMCVT-229 lts

- roles/node_images_ncn_common/files/scripts/metal/metal-lib.sh
- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASMINST-6532
The cmstools RPM doesn't work on storage NCNs. Historically we didn't install it there, but somewhere along the line we started doing it. This PR modifies the relevant script so that it doesn't get installed onto storage NCNs.
Low risk -- I am using the same method to check the NCN identity as is used in another function in the same file. I tested the shell script changes in isolation and they worked as expected.
> CASMINST-6532: Do not install cmstools on storage NCNs

- roles/node_images_management/vars/services/suse.yml
> CASMTRIAGE-5660: enable csm-node-heartbeat service

- roles/node_images_base/vars/packages/suse.yml
> MTL-2191 1.6

- roles/node_images_hypervisor/defaults/main.yml
- roles/node_images_hypervisor/files/sysctl.d/99-hypervisor.conf
- roles/node_images_hypervisor/vars/packages/suse.yml
- roles/node_images_management/files/cloud.cfg
- roles/node_images_management/files/cloud.cfg.d/00-network.cfg
- roles/node_images_management/tasks/main.yml
- roles/node_images_management/vars/packages/suse.yml
- roles/node_images_management/vars/services/suse.yml
> Sysctl, modules, and package updates

- roles/node_images_ncn_common/files/cloud.cfg
#279 changed this by accident.
> Undo `cloud.cfg` change

- Jenkinsfile.github
- roles/node_images_application/vars/packages/suse.yml
- roles/node_images_compute/vars/packages/suse.yml
- roles/packages_csm/vars/packages/suse.yml
> CASMTRIAGE-5649: new version of node-identity

- Jenkinsfile.github
> Also check the new VM images

- roles/node_images_hypervisor/vars/packages/suse.yml
Fixes: https://github.com/Cray-HPE/node-images/actions/runs/5573448818/jobs/10180737915#step:9:28
> New frr 1.5

- roles/node_images_ncn_common/vars/packages/suse.yml
https://github.com/Cray-HPE/csm/pull/2545
https://github.com/Cray-HPE/csm/pull/2560
> CASMINST-6538/CASMINST-6523: Run CMS/HMS tests w/main Goss health check; add troubleshooting info to CMS/HMS test files; use updated iPXE check

- roles/node_images_application/vars/packages/suse.yml
- roles/node_images_compute/vars/packages/suse.yml
- roles/node_images_ncn_common/vars/packages/suse.yml
metal-provision manifest PR for https://github.com/Cray-HPE/csm/pull/2582
> CASMCMS-8713: Update to PyYAML 6.0.1 to prevent build failures

- Jenkinsfile.github
We weren't actually validating all of the package files. We are now.
Yes
N/A
> fix package validation

- Jenkinsfile.github
Backport 1.5
We weren't actually validating all of the package files. We are now.
Yes
N/A
> fix package validation backport 1.5

- roles/packages_csm/vars/packages/suse.yml
- pin python3-websocket-client
Yes
N/A
> pin python3-websocket-client

- roles/packages_csm/vars/packages/suse.yml
- pin python3-websocket-client
Yes
N/A
> pin python3-websocket-client -- 1.5

- roles/node_images_ncn_common/vars/packages/suse.yml
CASMCVT-237
- Fixes: Latest fixes have been included for CDS
- Requires: new version built to be included
- Relates to:cvt-1.5.5-20230721101203_155d6ad01475.x86_64.rpm
> CASMCVT-237

- roles/packages_user/vars/packages/suse.yml
Patching additional packages while patching for Zenbleed in node-images.
CVE-2023-3446
CVE-2023-32001
CVE-2023-2911
> security updates

- roles/packages_user/vars/packages/suse.yml
Patching additional packages while patching for Zenbleed in node-images.
CVE-2023-3446
CVE-2023-32001
CVE-2023-2911
> security updates 1.5

- roles/node_images_ncn_common/files/scripts/metal/metal-lib.sh
> CASMINST-6578: install cani along with canu, et al during cloud-init

- roles/node_images_kubernetes_vm/vars/packages/suse.yml
- roles/node_images_management_vm/vars/packages/suse.yml
- roles/node_images_ncn_common/vars/packages/suse.yml
> CASMTRIAGE-5819: bump ceph-common version

- roles/node_images_application/vars/packages/suse.yml
- roles/node_images_compute/vars/packages/suse.yml
metal-provision 1.5 PR for https://github.com/Cray-HPE/csm/pull/2666
> CASMCMS-8753/CASMCMS-8755: BOS bug fixes

- scripts/packer/cleanup-functions.sh
- Fixes: log output
yes
None known.
> fix log output for repo/rpm association

- roles/node_images_application/vars/packages/suse.yml
- roles/node_images_compute/vars/packages/suse.yml
- roles/node_images_ncn_common/vars/packages/suse.yml
metal-provision CSM 1.5 PR for https://github.com/Cray-HPE/csm/pull/2703
> CASMCMS-8691: Use noos CMS RPMs

- roles/node_images_compute/vars/packages/suse-aarch64.yml
- roles/node_images_compute/vars/packages/suse-x86_64.yml
- roles/node_images_compute/vars/packages/suse.yml
- scripts/repos/compute.template.repos
- scripts/repos/cray.template.repos
Stop using cos-2.5 / sp4 repos and start using cos-2.6 / sp5 repos.
Yes
None known.
> updates for cos-2.6

- roles/node_images_ncn_kubernetes/vars/packages/suse.yml
- Relates to: [CASM-3723](https://jira-pro.it.hpe.com:8443/browse/CASM-3723)
Updating prodmgr version to be added as part of CSM 1.5
> CASM-3723 Updating prodmgr version

- roles/node_images_application/vars/packages/suse.yml
- roles/node_images_compute/vars/packages/suse.yml
https://github.com/Cray-HPE/csm/pull/2743
> CASMCMS-8770: List spire-agent as requirement for bos-reporter RPM to work

- roles/node_images_base/vars/packages/suse.yml
- scripts/repos/suse.template.repos
- Relates to: #376 
The previously used PTF 1213185 RPMs were for SLE-15-SP4, despite these working in testing it would be more appropriate to replace them with SP5 variaents.
The new repo URL also contains aarch64 RPMs, which were missed in the recent PTF addition. This will unblock aarch64 builds.
Lastly, I reorganized Artifactory to use a different directory structure for the PTF packages. The URLs for the previous PTF and new PTF are updated to reflect this.
> MTL-2253 Add SP5 RPMs with aarch64

- roles/node_images_application/vars/packages/suse.yml
- roles/node_images_compute/vars/packages/suse.yml
- roles/node_images_ncn_common/vars/packages/suse.yml
https://github.com/Cray-HPE/csm/pull/2745
> CASMCMS-8770: List spire-agent as requirement for cfs-state-reporter

- roles/cloud_init/vars/packages/suse.yml
- roles/node_images_base/vars/packages/suse-aarch64.yml
- roles/node_images_base/vars/packages/suse-x86_64.yml
- roles/node_images_base/vars/packages/suse.yml
- roles/node_images_compute/vars/packages/suse-aarch64.yml
- roles/node_images_compute/vars/packages/suse-x86_64.yml
- roles/node_images_compute/vars/packages/suse.yml
- roles/node_images_management_vm/vars/packages/suse.yml
- roles/node_images_ncn_common/vars/packages/suse.yml
- roles/node_images_ncn_kubernetes/vars/packages/suse.yml
- roles/node_images_pre_install_toolkit/vars/packages/suse.yml
- roles/packages_csm/vars/packages/suse.yml
- scripts/repos/suse.template.repos
- Fixes: sles15-base builds and listed CVEs
This updates a few packages that came in via our base image, without them any image build that includes a base image is broken.
This also includes a few misc. updates discovered along the way.
python3-websocket-client:
- CVE-2018-1000518
- CVE-2020-25659
- CVE-2020-36242
- CVE-2021-22569
- CVE-2021-22570
- CVE-2022-1941
- CVE-2022-3171
> Package sweep and build fixes

- roles/packages_user/vars/packages/suse.yml
Missed by the updated, the update script did not update the manifest.
Not sure why, will dig into later.
> user package update

- roles/node_images_hypervisor/tasks/main.yml
https://github.com/Cray-HPE/node-images/actions/runs/6002780100/job/16280196407#step:10:20367
> Missed dict key

- roles/node_images_hypervisor/tasks/main.yml
https://github.com/Cray-HPE/node-images/actions/runs/6003803251/job/16283437805?pr=908#step:10:20407
> Wrong path

- group_vars/management_vm/packages.suse.yml
- group_vars/management_vm/services.suse.yml
- pb_node_images_management-vm.yml
- roles/gitea/defaults/main.yml
- roles/gitea/handlers/main.yml
- roles/gitea/tasks/main.yml
- roles/gitea/templates/gitea.ini.j2
- roles/gitea/templates/gitea.service.j2
- roles/gitea/vars/main.yml
- vars/fawkes.yml
- adds ansible role for installing and configuring **gitea** (written by @manderson-hpe, stolen by @jpdavis-prof)
Yes
None
> MTL-2247 partial -- adds gitea role

- group_vars/application/packages.suse.yml
- group_vars/compute/packages.suse.yml
- vars/packages/csm.suse.yml
- upgrade csm-node-heartbeat
Yes
None known.
> CASMTRIAGE-5999

- roles/node_images/files/scripts/common/openscap.sh
- Fixes:
- Requires:
- Relates to:
> Add var to gate oscap execution

- vars/packages/csm.suse.yml
https://github.com/Cray-HPE/craycli/pull/130
> CASMCMS-8723 Update CFS cli for v3/paging changes

- group_vars/fawkes_live/packages.suse.yml
- group_vars/hypervisor/packages.suse.yml
- Relates to: https://github.com/Cray-HPE/crucible/pull/17
Includes new code for installing to disk from http boots, as well as importing ssh-keys from gitea during a disk install.
> New crucible with HTTP Boot Installs

- group_vars/ncn_metal/packages.suse.yml
> MTL-2272: use default xfs options

- roles/node_images/files/scripts/common/openscap.sh
retry on all curl failures for openscap dl's
- Fixes: curl failures
- Requires:
- Relates to:
> curl retries

- roles/node_images/files/scripts/common/openscap.sh
add more curl retries
Yes
None known
> more curl retries

- roles/node_images/files/scripts/common/openscap.sh
wget w/o progress bar
Yes
None known
> wget w/o progress bar

- roles/node_images/files/scripts/common/openscap.sh
wget w/o progress bar
Yes
None known
> wget w/o progress bar -- 1.5

- roles/gitea/handlers/main.yml
- roles/gitea/tasks/main.yml
- Fixes:
- Requires:
- Relates to:
Add migration step to the Ansible, removing it from docs.
https://github.com/Cray-HPE/fawkes-docs/pull/18
> Gitea tweaks

- roles/gitea/defaults/main.yml
> Missed commit

- vars/packages/csm.suse.yml
- vars/packages/suse.x86_64.yml
MTL-2279: add msr-tools
CASMTRIAGE-6061: update spire agent
- Fixes: MTL-2279, CASMTRIAGE-6061
> Add msr-tools, update spire-agent

- group_vars/ncn/packages.suse.yml
https://github.com/Cray-HPE/csm/pull/2857
> CASMCMS-8812: Skip CMS conman Goss test on vshasta

- vars/packages/csm.suse.yml
> CASMINST-6665: bump csm-node-heartbeat version

- group_vars/pre_install_toolkit/packages.suse.yml
Add ACL for DHCP
Fix CANU exit code on BGP validation
- Fixes: CASMNET-2017 CASMNET-2158
- Requires:
- Relates to:
> CASMNET-2017 1.5

- group_vars/pre_install_toolkit/packages.suse.yml
Add ACL for DHCP
Fix CANU exit code on BGP validation
- Fixes: CASMNET-2017 CASMNET-2158
- Requires:
- Relates to:
> CASMNET-2017 main

- group_vars/compute/packages.suse.yml
- group_vars/ncn/packages.suse.yml
> CASMTRIAGE-6117: cfs-state-reporter version bump

- group_vars/ncn/packages.suse.yml
- scripts/repos/cray.template.repos
Earlier we were installing sma cli rpm as part of sma cfs configuration. But now we need to have this rpm installation as part of csm installation.
https://jira-pro.it.hpe.com:8443/browse/CASM-4520
DST sync PR has been merged: https://github.com/Cray-HPE/dst-sync/pull/14
- Fixes:
- Requires:
- Relates to:
> CASMSMF-7462: add sma-cli-utils rpm

- vars/packages/suse.yml
> CVE: curl version bump

- scripts/repos/cray.template.repos
- scripts/repos/suse.template.repos
- Fixes: CASMINST-6683
Adds the new
https://artifactory.algol60.net/artifactory/suse-external/PTF.1214754/15-SP5/ repository an LACP bond fix.
Official maintenance update should be released by SUSE on 11/4/2023 (https://scc.suse.com/support/cases/00703657#02s5q00000f9LlbAAE).
> CASMINST-6683 Add PTF.1214754 RPMs - fix LACP bond

- .editorconfig
- scripts/get-package-list-from-inventory.py
- scripts/get-packages.py
- scripts/packer/cleanup-functions.sh
- scripts/packer/setup-functions.sh
- scripts/rpm-functions.sh
This PR merges in the `node-images/boxes/*base/provisioners/common/{setup,cleanup}.sh` functions.
node-images base boxes will now pull in metal-provision, and use the included `setup-functions.sh` and `cleanup-functions.sh`.
> Merge base box packer functions 1.5

- scripts/nexus/setup-nexus.sh
- Relates to: https://github.com/Cray-HPE/metal-nexus/pull/24
When uploading docker images, also ensure the registry is created.
This needs to be merged before https://github.com/Cray-HPE/metal-nexus/pull/24
> Create registry on upload

- group_vars/management_vm/packages.suse.yml
- group_vars/pre_install_toolkit/packages.suse.yml
https://github.com/Cray-HPE/metal-provision/pull/550
https://github.com/Cray-HPE/metal-nexus/pull/24
> MTL-2298 Use new metal-nexus

- group_vars/ncn/packages.suse.yml
- scripts/repos/cray.template.repos
Few files were missing in the earlier version of sma-cli-utils rpm and had to rebuild the new rpm with the fix.
Jira: https://jira-pro.it.hpe.com:8443/browse/CASMSMF-7515
> CASMSMF-7515: update sma-cli-utils rpm version

- group_vars/pre_install_toolkit/packages.suse.yml
Pulls in https://github.com/Cray-HPE/cray-site-init/pull/347
> CASMTRIAGE-6178 `csi` fixes for MTL-2000

- group_vars/fawkes_live/packages.suse.yml
- group_vars/hypervisor/packages.suse.yml
Pulls in a newer `crucible` that installs hypervisors using the new disk layout.
> MTL-2284 Pull in new `crucible`

- Jenkinsfile.github
- scripts/repos/cray.template.repos
Use slingshot release repo instead of the dev repo.
Ref: https://github.com/Cray-HPE/dst-sync/pull/15
none known
> use slingshot release repo

- group_vars/ncn/packages.suse.yml
> MTL-2092: update cloud-init for CVE remediation

- group_vars/pre_install_toolkit/packages.suse.yml
- Fixes:
- Requires:
- Relates to:
> MTL-2351 and MTL-2352

- group_vars/ncn/packages.suse.yml
https://github.com/Cray-HPE/csm/pull/3080
> CASMINST-6736: Improve logging of several Goss tests

- group_vars/kubernetes/packages.suse.yml
- group_vars/kubernetes/services.suse.yml
- vars/packages/csm.suse.yml
> CASMPET-6797: rpms to support LIO services

- group_vars/compute/packages.suse.yml
metal-provision PR for https://github.com/Cray-HPE/csm/pull/3101
> CASMCMS-8880: Update etcd base chart version; Pin Alpine version

- group_vars/fawkes_live/packages.suse.yml
- group_vars/hypervisor/packages.suse.yml
Includes fixes from https://github.com/Cray-HPE/crucible/pull/33
> New crucible 0.0.16

- .config/ansible-lint-ignore.txt
- pb_k3s.yml
- roles/k3s_agent/tasks/main.yml
- roles/k3s_agent/templates/k3s.service.j2
- roles/k3s_prep/defaults/main.yml
- roles/k3s_prep/tasks/main.yml
- roles/k3s_server/defaults/main.yml
- roles/k3s_server/tasks/main.yml
- roles/k3s_server/templates/k3s.service.j2
- roles/k3s_setup/tasks/main.yml
- roles/k3s_setup/templates/registries.yaml.j2
- roles/metallb/defaults/main.yml
- roles/metallb/tasks/main.yml
- roles/metallb/templates/metallb-crds.yaml.j2
- roles/metallb/templates/metallb-crs.yaml.j2
- vars/k3s.yml
- Fixes:
- Requires:
- Relates to:
> MTL-2297 Add k3s Roles

- group_vars/fawkes_live/packages.suse.yml
- group_vars/hypervisor/packages.suse.yml
Pulls in https://github.com/Cray-HPE/crucible/pull/34
> MTL-2367 Crucible 0.0.17

- group_vars/fawkes_live/packages.suse.yml
- group_vars/hypervisor/packages.suse.yml
- group_vars/management_vm/packages.suse.x86_64.yml
- group_vars/management_vm/packages.suse.yml
- pb_node_images_fawkes-live.yml
- pb_node_images_hypervisor.yml
- pb_node_images_kubernetes-vm.yml
- pb_node_images_management-vm.yml
- roles/node_images_metal/files/scripts/metal/create-iso-artifact.sh
- vars/packages/suse.aarch64.yml
https://jira-pro.it.hpe.com:8443/browse/MTL-2355
- build fawkes artifacts for aarch64
yes
None known.
> MTL-2355 Build aarch64 Variants of Fawkes for developers

- roles/node_images/tasks/main.yml
- scripts/packer/cleanup-functions.sh
> MTL-2375 Follow-up - Ansible

- vars/packages/suse.yml
- fix non-fatal build errors. Adding two packages.
none known
> add packages required by kdump/dracut

- group_vars/ncn/packages.suse.yml
- scripts/repos/cray.template.repos
- remove sma-cli-utils
None known. sma-cli-utils is now installed via cloud-init.
> remove sma-cli-utils

- group_vars/compute/packages.suse.yml
https://github.com/Cray-HPE/csm/pull/3180
> CASMCMS-8916: Fix bugs with BOS v2 components PATCH/PUT

- group_vars/compute/packages.suse.yml
- group_vars/ncn/packages.suse.yml
https://github.com/Cray-HPE/csm/pull/3194
> CASMCMS-8914: Use appropriate version of Python kubernetes module

- vars/packages/csm.suse.yml
https://github.com/Cray-HPE/csm/pull/3224
> CASMCMS-8903: Remove BOSv1 from Cray CLI

- group_vars/fawkes_live/packages.suse.yml
- group_vars/hypervisor/packages.suse.yml
- group_vars/kubernetes_vm/packages.suse.yml
- group_vars/management_vm/packages.suse.x86_64.yml
- group_vars/management_vm/packages.suse.yml
- group_vars/ncn/packages.suse.yml
- group_vars/pre_install_toolkit/packages.suse.yml
- vars/packages/csm.suse.yml
- vars/packages/suse.aarch64.yml
- vars/packages/suse.x86_64.yml
- vars/packages/suse.yml
> Package updates

- group_vars/kubernetes/packages.suse.yml
https://github.com/Cray-HPE/csm/pull/3243
> CASMTRIAGE-6662/CASMPET-6924: ncnHealthChecks.sh: Improvements and fixes

- group_vars/compute/packages.suse.yml
https://github.com/Cray-HPE/csm/pull/3248
> CASMCMS-8947/CASMCMS-7329: Remove BOS v1; avoid plugin error

- group_vars/compute/packages.suse.x86_64.yml
- group_vars/compute/packages.suse.yml
- group_vars/google/packages.suse.yml
- group_vars/metal/packages.suse.x86_64.yml
- scripts/repos/cray.template.repos
- scripts/repos/hpe.template.repos
- scripts/rpm-functions.sh
- vars/packages/cloud-init.suse.yml
- vars/packages/suse.aarch64.yml
- vars/packages/suse.x86_64.yml
- vars/packages/suse.yml
> MTL-2383 Package sweep

- group_vars/kubernetes/packages.suse.yml
- group_vars/kubernetes_metal/packages.suse.yml
- Fixes: https://jira-pro.it.hpe.com:8443/browse/MTL-2364
- Pulls in changes from: https://github.com/Cray-HPE/dracut-metal-dmk8s/pull/36
yes
none known
> MTL-2364 -- 1.6

- vars/packages/csm.suse.yml
- Relates to: [CASMHMS-6154](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6154)
> Updated craycli version to 0.83.2

- requirements.yml
- roles/dnsmasq/defaults/main.yml
- roles/dnsmasq/templates/dnsmasq.d/LOCAL.conf.j2
- roles/network_manager/tasks/main.yml
- Fixes:
- Requires:
- Relates to:
This enables DNS resolution on the hypervisor node hosting the management-VM by configuring DNS queries to go over the isolated network.
Yes.
> DNS for local hypervisor

- group_vars/pre_install_toolkit/packages.suse.yml
- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASMINST-5905
none known
> CASMINST-5905

- group_vars/management_vm/packages.suse.yml
- group_vars/ncn/packages.suse.yml
- group_vars/pre_install_toolkit/packages.suse.yml
- vars/packages/cloud-init.suse.yml
- vars/packages/suse.aarch64.yml
- vars/packages/suse.yml
- vars/packages/user.suse.yml
- https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7012
- https://jira-pro.it.hpe.com:8443/browse/MTL-2388
- misc. package updates
> CASMTRIAGE-7012, MTL-2388, general package updates

- group_vars/compute/packages.suse.yml
This pulls in the fix for https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7019
> CASMTRIAGE-7019: BOS reporter RPM update

- group_vars/fawkes_live/packages.suse.yml
- group_vars/hypervisor/packages.suse.yml
- group_vars/management_vm/packages.suse.yml
- hypervisor.yml
- roles/network_manager/tasks/main.yml
Set the hostname on the target nodes.
> Fawkes - Set hostnames

- roles/node_images_ncn/files/tests/common/ncn-common-tests.yml
- roles/node_images_ncn/tasks/main.yml
- vars/services/csm.suse.yml
- Fixes: https://jira-pro.it.hpe.com:8443/browse/MTL-2402
yes
> MTL-2402 -- 1.6

- group_vars/pre_install_toolkit/packages.suse.yml
https://github.com/Cray-HPE/cray-site-init/pull/391
> MTL-2396 New CSI

- group_vars/pre_install_toolkit/packages.suse.yml
Shell completion for CSI (BASH and ZSH).
Includes some minor updates to CSI dependencies.
> MTL-2403 Shell completion for CSI

- group_vars/pre_install_toolkit/packages.suse.yml
- Fixes: MTL-2424
- Relates to: #691 
Fixes `MTL.conf` generation for `packages.local` to resolve properly during cloud-init.
https://github.com/Cray-HPE/cray-site-init/pull/407
> MTL-2424 New CSI

- group_vars/pre_install_toolkit/packages.suse.yml
https://github.com/Cray-HPE/cray-site-init/pull/413
> MTL-2444 Typo in csi error message for CHN

- group_vars/compute/packages.suse.yml
- Fixes: [CASMCMS-9081](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9081)
Update to a version of BOS reporter that is not broken. :)
> CASMCMS-9081: Fix bug in bos-reporter preventing it from working
